/* chitti_fashion_dyn.js — localize the engine's DYNAMIC output (occasion names,
   harmony, confidence, judge verdicts, swarm chrome, explain templates) into the
   9 primary Vaani languages. Engine returns language-neutral CODES; this maps them.
   Falls back to English for any missing token. v20260604 */
(function () {
  'use strict';
  var D = {
    en: {
      occ: { casual:'casual', 'smart-casual':'smart-casual', 'business-casual':'business-casual', formal:'formal', festive:'festive', wedding:'wedding', office:'office', interview:'interview', college:'college', religious:'religious', date:'date night', travel:'travel', funeral:'funeral', family:'family function' },
      harm: { single:'one colour — always safe', 'neutral-anchored':'a neutral lets one colour lead — clean and intentional', monochrome:'one colour family reads cohesive', 'two-tone':'two families with balanced contrast', mixed:'several families — a neutral would calm it', competing:'two brights compete — anchor with a neutral' },
      agent: { fashion:'👗 Style', color:'🎨 Colour', occasion:'🎉 Occasion', comfort:'😌 Comfort', accessibility:'♿ For everyone', sustainability:'♻️ Sustainability', budget:'💸 Budget', climate:'🌦️ Climate', cultural:'🪔 Cultural', confidence:'✨ Confidence' },
      agentwhy: { sustain:'re-wearable — cost-per-wear drops', climate_ok:'fabric suits the season', cultural_ok:'respects the occasion' },
      chrome: { experts:'9 experts say', open:'(open)', trend:'📈 Trend (info only): ', whyq:'🎓 Why, Chitti? (learn)', why:'Why', benefits:'Benefits', tradeoffs:'Trade-offs', alts:'Alternatives', free:'✅ Free (from your wardrobe · ₹0)', cheap:'💸 Budget option', premium:'⭐ Premium', conf:'Confidence', checks_pass:'checks pass' },
      conf: { occasion:'occasion', color:'colour', weather:'weather', budget:'budget', accessibility:'accessibility' },
      judge: { cultural:'cultural', weather:'weather', age:'age', accessibility:'accessibility', funeral_bright:'bright/red reads festive — funerals call for white or muted', wedding_white:'all-white at a wedding can read as mourning in many communities — confirm', season_mismatch:'fabric leans the other season — adjust your layers', senior_footwear:'prefer non-slip, easy-fasten footwear for comfort and safety', child_safety:'keep it comfortable and safe for a child', easy_fasten:'prefer magnetic/velcro/front-open for independent dressing' },
      tmpl: { reads:'This reads {occ} (formality {band}/5). Colour: {harm}.', wear:'You can wear: {items}. This reads {occ} and is good to go.', built:'{n} outfits from clothes you already own — ₹0', made:'I built {n} outfits from your wardrobe', just:'✅ just right for {occ}', over:'⬆️ a bit over-dressed for {occ}', under:'⬇️ a bit too casual for {occ}', overall:'Overall {n}/10' },
      // ── CFOS v2.1 dynamic output ──
      repair: {
        // damage chips (icon + label)
        dmg_tear_small:'✂️ Small tear', dmg_tear_large:'🩹 Big tear', dmg_button_missing:'🔘 Button off', dmg_hem_loose:'〰️ Loose hem', dmg_seam_open:'➰ Open seam', dmg_zip_broken:'🤐 Broken zip', dmg_hole_knit:'🕳️ Knit hole', dmg_stain_oil:'🟤 Oil stain', dmg_stain_ink:'🖊️ Ink stain', dmg_too_tight:'➖ Too tight', dmg_too_loose:'➕ Too loose', dmg_fade:'🌗 Faded',
        // difficulty + verdict
        easy:'Easy', medium:'Medium', hard:'Hard', diy_yes:'✅ You can do this at home', diy_no:'🧵 Best done by a tailor', tailor_too:'(a tailor can also do it)', minutes:'min', tools:'You need', steps:'Steps', find_tailor:'🔎 Find a tailor near me', mark_repair:'🩺 Mark: needs repair', mark_repaired:'✅ Mark: repaired', ladder_note:'Repair before you buy — Founder Rule.', plan_title:'Repair plan',
        // step text
        turn_inside:'Turn the garment inside out', align_edges:'Bring the torn edges together', thread_needle:'Thread the needle and knot the end', stitch_back:'Backstitch along the line, small and even', knot_off:'Knot off and trim the thread', cut_patch:'Cut a patch slightly bigger than the tear', pin_patch:'Pin the patch behind the hole', stitch_around:'Stitch all around the patch', press_iron:'Press flat with a warm iron', position_button:'Place the button where it sits', sew_xcross:'Sew through the holes in an X', wrap_shank:'Wrap the thread under to make a shank', fold_hem:'Fold the hem to the old crease', pin_hem:'Pin the fold in place', blind_stitch:'Blind-stitch so it does not show outside', align_seam:'Line up the open seam', unpick_old:'Unpick the old zip with a seam-ripper', pin_newzip:'Pin the new zip in place', tailor_recommend:'Take it to a tailor — this one is fiddly', span_hole:'Span the hole with the darning needle', darn_warp:'Lay rows of thread one way', darn_weft:'Weave across the other way', blot_excess:'Blot the excess — do not rub it in', apply_soap:'Work in a little dish soap', rub_gentle:'Rub gently from the outside in', rinse_warm:'Rinse with warm water', air_dry:'Air-dry in shade', apply_alcohol:'Dab rubbing alcohol on the stain', dab_lift:'Dab to lift the ink onto cotton', rinse_cool:'Rinse with cool water', wash_clean:'Wash the garment clean first', mix_dye:'Mix the dye as on the pack', soak_even:'Soak evenly, stirring slowly', rinse_clear:'Rinse until the water runs clear'
      },
      wedding: {
        fn_mehendi:'Mehendi', fn_sangeet:'Sangeet', fn_wedding:'Wedding', fn_reception:'Reception',
        role_own:'It is my function', role_sibling:'Sibling’s', role_friend:'Friend’s', role_colleague:'Colleague’s',
        cul_north:'North Indian', cul_south:'South Indian', cul_bengali:'Bengali', cul_punjabi:'Punjabi', cul_rajasthani:'Rajasthani', cul_maharashtrian:'Maharashtrian', cul_other:'Other',
        anchor:'⭐ Lead look', accent:'🎀 Coordinated', theme:'Family theme', warm:'warm — maroon, gold, rust read as one set', cool:'cool — navy, teal, plum read as one set',
        coordination:'Coordination', plan_title:'Family wedding plan', gap_no_festive:'No festive wear yet', borrow:'borrow in the family', rent:'rent', buy:'buy (last option)', borrow_from:'borrow from'
      },
      week: {
        Mon:'Monday', Tue:'Tuesday', Wed:'Wednesday', Thu:'Thursday', Fri:'Friday',
        dc_casual:'Casual', dc_smart:'Smart', dc_formal:'Formal', wx_hot:'☀️ Hot', wx_cold:'❄️ Cold', wx_mod:'⛅ Mild',
        reused:'♻️ same pieces, fresh pairing', variety:'Variety', plan_title:'Your office week', honest_tip:'Add 1–2 bottoms to unlock a no-repeat week', dress_code:'Dress code', weather:'Weather'
      },
    },
    hi: {
      occ: { casual:'रोज़', 'smart-casual':'स्मार्ट-कैज़ुअल', 'business-casual':'बिज़नेस-कैज़ुअल', formal:'फ़ॉर्मल', festive:'त्योहारी', wedding:'शादी', office:'दफ़्तर', interview:'इंटरव्यू', college:'कॉलेज', religious:'धार्मिक', date:'डेट नाइट', travel:'यात्रा', funeral:'शोक', family:'पारिवारिक समारोह' },
      harm: { single:'एक रंग — हमेशा सुरक्षित', 'neutral-anchored':'एक neutral रंग बाक़ी को निखारता है — साफ़ और सोचा-समझा', monochrome:'एक ही रंग-परिवार सुसंगत लगता है', 'two-tone':'दो रंग-परिवार, संतुलित कंट्रास्ट', mixed:'कई रंग — एक neutral इसे शांत करेगा', competing:'दो चटक रंग टकराते हैं — एक neutral जोड़ें' },
      agent: { fashion:'👗 स्टाइल', color:'🎨 रंग', occasion:'🎉 मौक़ा', comfort:'😌 आराम', accessibility:'♿ सबके लिए', sustainability:'♻️ टिकाऊपन', budget:'💸 बजट', climate:'🌦️ मौसम', cultural:'🪔 सांस्कृतिक', confidence:'✨ आत्मविश्वास' },
      agentwhy: { sustain:'फिर पहनने योग्य — प्रति बार लागत घटती है', climate_ok:'कपड़ा मौसम के अनुकूल है', cultural_ok:'मौक़े का सम्मान करता है' },
      chrome: { experts:'9 विशेषज्ञों की राय', open:'(खोलें)', trend:'📈 ट्रेंड (सिर्फ़ जानकारी): ', whyq:'🎓 क्यों, Chitti? (समझें)', why:'क्यों', benefits:'फ़ायदे', tradeoffs:'समझौते', alts:'विकल्प', free:'✅ मुफ़्त (आपकी अलमारी से · ₹0)', cheap:'💸 सस्ता विकल्प', premium:'⭐ प्रीमियम', conf:'आत्मविश्वास', checks_pass:'जाँच पास' },
      conf: { occasion:'मौक़ा', color:'रंग', weather:'मौसम', budget:'बजट', accessibility:'सबके लिए' },
      judge: { cultural:'सांस्कृतिक', weather:'मौसम', age:'उम्र', accessibility:'सबके लिए', funeral_bright:'चटक/लाल रंग त्योहारी लगता है — शोक में सफ़ेद या हल्के रंग', wedding_white:'शादी में पूरा सफ़ेद कई समुदायों में शोक जैसा लगता है — पुष्टि करें', season_mismatch:'कपड़ा दूसरे मौसम का है — layer ठीक करें', senior_footwear:'आराम और सुरक्षा के लिए non-slip, आसान जूते बेहतर', child_safety:'बच्चे के लिए आरामदायक और सुरक्षित रखें', easy_fasten:'ख़ुद पहनने के लिए magnetic/velcro/front-open बेहतर' },
      tmpl: { reads:'यह {occ} लगता है (formality {band}/5)। रंग: {harm}।', wear:'आप पहन सकते हैं: {items}। यह {occ} के लिए सही है।', built:'{n} पहनावे आपके अपने कपड़ों से — ₹0', made:'मैंने आपकी अलमारी से {n} पहनावे बनाए', just:'✅ {occ} के लिए सही', over:'⬆️ {occ} के लिए थोड़ा ज़्यादा formal', under:'⬇️ {occ} के लिए थोड़ा casual', overall:'कुल {n}/10' },
      repair: {
        dmg_tear_small:'✂️ छोटा फटाव', dmg_tear_large:'🩹 बड़ा फटाव', dmg_button_missing:'🔘 बटन टूटा', dmg_hem_loose:'〰️ किनारा ढीला', dmg_seam_open:'➰ सिलाई खुली', dmg_zip_broken:'🤐 ज़िप ख़राब', dmg_hole_knit:'🕳️ बुनाई में छेद', dmg_stain_oil:'🟤 तेल का दाग़', dmg_stain_ink:'🖊️ स्याही का दाग़', dmg_too_tight:'➖ बहुत तंग', dmg_too_loose:'➕ बहुत ढीला', dmg_fade:'🌗 रंग उड़ा',
        easy:'आसान', medium:'मध्यम', hard:'मुश्किल', diy_yes:'✅ यह घर पर हो जाएगा', diy_no:'🧵 दर्ज़ी से करवाना बेहतर', tailor_too:'(दर्ज़ी भी कर सकता है)', minutes:'मिनट', tools:'चाहिए', steps:'तरीक़ा', find_tailor:'🔎 पास का दर्ज़ी ढूँढो', mark_repair:'🩺 निशान: मरम्मत चाहिए', mark_repaired:'✅ निशान: ठीक हो गया', ladder_note:'खरीदने से पहले मरम्मत — Founder Rule।', plan_title:'मरम्मत का तरीक़ा',
        turn_inside:'कपड़े को उल्टा कर लें', align_edges:'फटे किनारों को मिलाएँ', thread_needle:'सूई में धागा डालें, सिरे पर गाँठ', stitch_back:'लाइन पर छोटे, बराबर बैकस्टिच करें', knot_off:'गाँठ लगाकर धागा काट दें', cut_patch:'फटाव से थोड़ा बड़ा पैच काटें', pin_patch:'छेद के पीछे पैच पिन करें', stitch_around:'पैच के चारों ओर सिलाई करें', press_iron:'गरम इस्त्री से दबाएँ', position_button:'बटन को सही जगह रखें', sew_xcross:'छेदों में X आकार में सिलें', wrap_shank:'नीचे धागा लपेटकर shank बनाएँ', fold_hem:'किनारे को पुरानी तह पर मोड़ें', pin_hem:'तह को पिन करें', blind_stitch:'ब्लाइंड-स्टिच करें ताकि बाहर न दिखे', align_seam:'खुली सिलाई को मिलाएँ', unpick_old:'सीम-रिपर से पुरानी ज़िप खोलें', pin_newzip:'नई ज़िप पिन करें', tailor_recommend:'दर्ज़ी के पास ले जाएँ — यह बारीक काम है', span_hole:'डार्निंग सूई से छेद को घेरें', darn_warp:'एक तरफ़ धागे की कतारें बिछाएँ', darn_weft:'दूसरी तरफ़ बुनाई करें', blot_excess:'ज़्यादा को सोखें — रगड़ें नहीं', apply_soap:'थोड़ा डिश साबुन लगाएँ', rub_gentle:'बाहर से अंदर की ओर हल्के रगड़ें', rinse_warm:'गुनगुने पानी से धोएँ', air_dry:'छाँव में सुखाएँ', apply_alcohol:'दाग़ पर रबिंग अल्कोहल लगाएँ', dab_lift:'रुई से थपथपाकर स्याही उठाएँ', rinse_cool:'ठंडे पानी से धोएँ', wash_clean:'पहले कपड़ा साफ़ धो लें', mix_dye:'पैक के अनुसार डाई घोलें', soak_even:'धीरे हिलाते हुए बराबर भिगोएँ', rinse_clear:'जब तक पानी साफ़ न आए धोएँ'
      },
      wedding: {
        fn_mehendi:'मेहंदी', fn_sangeet:'संगीत', fn_wedding:'शादी', fn_reception:'रिसेप्शन',
        role_own:'मेरा अपना फ़ंक्शन', role_sibling:'भाई/बहन का', role_friend:'दोस्त का', role_colleague:'सहकर्मी का',
        cul_north:'उत्तर भारतीय', cul_south:'दक्षिण भारतीय', cul_bengali:'बंगाली', cul_punjabi:'पंजाबी', cul_rajasthani:'राजस्थानी', cul_maharashtrian:'महाराष्ट्रीयन', cul_other:'अन्य',
        anchor:'⭐ मुख्य look', accent:'🎀 साथ में', theme:'परिवार की थीम', warm:'गरम — मरून, सुनहरा, रस्ट एक सेट जैसे', cool:'ठंडा — नेवी, टील, बैंगनी एक सेट जैसे',
        coordination:'तालमेल', plan_title:'परिवार का शादी प्लान', gap_no_festive:'अभी कोई त्योहारी पहनावा नहीं', borrow:'परिवार में उधार', rent:'किराया', buy:'खरीद (आख़िरी विकल्प)', borrow_from:'इनसे उधार'
      },
      week: {
        Mon:'सोमवार', Tue:'मंगलवार', Wed:'बुधवार', Thu:'गुरुवार', Fri:'शुक्रवार',
        dc_casual:'कैज़ुअल', dc_smart:'स्मार्ट', dc_formal:'फ़ॉर्मल', wx_hot:'☀️ गरम', wx_cold:'❄️ ठंडा', wx_mod:'⛅ हल्का',
        reused:'♻️ वही कपड़े, नई जोड़ी', variety:'विविधता', plan_title:'आपका ऑफ़िस सप्ताह', honest_tip:'1–2 नीचे के कपड़े जोड़ें — पूरा हफ़्ता बिना दोहराव', dress_code:'ड्रेस कोड', weather:'मौसम'
      },
    },
    ta: {
      occ: { casual:'தினசரி', 'smart-casual':'ஸ்மார்ட்-கேஷுவல்', 'business-casual':'பிசினஸ்-கேஷுவல்', formal:'முறையான', festive:'பண்டிகை', wedding:'திருமணம்', office:'அலுவலகம்', interview:'நேர்காணல்', college:'கல்லூரி', religious:'மத', date:'டேட் நைட்', travel:'பயணம்', funeral:'இரங்கல்', family:'குடும்ப விழா' },
      harm: { single:'ஒரே நிறம் — எப்போதும் பாதுகாப்பானது', 'neutral-anchored':'ஒரு நடுநிலை நிறம் மற்றதை மிளிரச் செய்கிறது — சுத்தமானது', monochrome:'ஒரே நிற குடும்பம் ஒத்திசைவாக இருக்கிறது', 'two-tone':'இரு நிற குடும்பங்கள், சமநிலை மாறுபாடு', mixed:'பல நிறங்கள் — ஒரு நடுநிலை நிறம் அமைதிப்படுத்தும்', competing:'இரு பிரகாச நிறங்கள் மோதுகின்றன — ஒரு நடுநிலை சேர்க்கவும்' },
      agent: { fashion:'👗 ஸ்டைல்', color:'🎨 நிறம்', occasion:'🎉 சந்தர்ப்பம்', comfort:'😌 வசதி', accessibility:'♿ அனைவருக்கும்', budget:'💸 பட்ஜெட்', sustainability:'♻️ நிலைத்தன்மை', climate:'🌦️ வானிலை', cultural:'🪔 கலாச்சாரம்', confidence:'✨ நம்பிக்கை' }, agentwhy: { sustain:'மீண்டும் அணியக்கூடியது', climate_ok:'துணி பருவத்திற்கு ஏற்றது', cultural_ok:'சந்தர்ப்பத்தை மதிக்கிறது' },
      chrome: { experts:'9 நிபுணர்களின் கருத்து', open:'(திற)', trend:'📈 டிரெண்ட் (தகவல் மட்டும்): ', whyq:'🎓 ஏன், Chitti? (கற்க)', why:'ஏன்', benefits:'நன்மைகள்', tradeoffs:'சமரசங்கள்', alts:'மாற்றுகள்', free:'✅ இலவசம் (உங்கள் அலமாரியிலிருந்து · ₹0)', cheap:'💸 மலிவான வழி', premium:'⭐ பிரீமியம்', conf:'நம்பிக்கை', checks_pass:'சரிபார்ப்புகள் சரி' },
      conf: { occasion:'சந்தர்ப்பம்', color:'நிறம்', weather:'வானிலை', budget:'பட்ஜெட்', accessibility:'அனைவருக்கும்' },
      judge: { cultural:'கலாச்சாரம்', weather:'வானிலை', age:'வயது', accessibility:'அணுகல்', funeral_bright:'பிரகாச/சிவப்பு நிறம் பண்டிகை போல் தெரிகிறது — இரங்கலுக்கு வெள்ளை அல்லது மென்நிறம்', wedding_white:'திருமணத்தில் முழு வெள்ளை சில சமூகங்களில் இரங்கல் போல் தெரியலாம் — உறுதிசெய்யவும்', season_mismatch:'துணி வேறு பருவத்திற்கானது — அடுக்குகளை சரிசெய்யவும்', senior_footwear:'வசதி, பாதுகாப்பிற்கு வழுக்காத, எளிதாக அணியும் காலணி நல்லது', child_safety:'குழந்தைக்கு வசதியாகவும் பாதுகாப்பாகவும் வைக்கவும்', easy_fasten:'தானே அணிய magnetic/velcro/front-open நல்லது' },
      tmpl: { reads:'இது {occ} போல் தெரிகிறது (formality {band}/5). நிறம்: {harm}.', wear:'நீங்கள் அணியலாம்: {items}. இது {occ}-க்கு சரியானது.', built:'{n} உடைகள் உங்கள் சொந்த ஆடைகளிலிருந்து — ₹0', made:'உங்கள் அலமாரியிலிருந்து {n} உடைகளை உருவாக்கினேன்', just:'✅ {occ}-க்கு சரியானது', over:'⬆️ {occ}-க்கு கொஞ்சம் அதிக முறையானது', under:'⬇️ {occ}-க்கு கொஞ்சம் கேஷுவல்', overall:'மொத்தம் {n}/10' },
    },
    bn: {
      occ: { casual:'প্রতিদিন', 'smart-casual':'স্মার্ট-ক্যাজুয়াল', 'business-casual':'বিজনেস-ক্যাজুয়াল', formal:'ফর্মাল', festive:'উৎসব', wedding:'বিয়ে', office:'অফিস', interview:'সাক্ষাৎকার', college:'কলেজ', religious:'ধর্মীয়', date:'ডেট নাইট', travel:'ভ্রমণ', funeral:'শোক', family:'পারিবারিক অনুষ্ঠান' },
      harm: { single:'একটি রঙ — সবসময় নিরাপদ', 'neutral-anchored':'একটি নিরপেক্ষ রঙ বাকিগুলোকে ফুটিয়ে তোলে — পরিষ্কার', monochrome:'একই রঙ-পরিবার সুসংগত লাগে', 'two-tone':'দুটি রঙ-পরিবার, ভারসাম্যপূর্ণ বৈসাদৃশ্য', mixed:'অনেক রঙ — একটি নিরপেক্ষ রঙ শান্ত করবে', competing:'দুটি উজ্জ্বল রঙ লড়ছে — একটি নিরপেক্ষ যোগ করুন' },
      agent: { fashion:'👗 স্টাইল', color:'🎨 রঙ', occasion:'🎉 উপলক্ষ', comfort:'😌 আরাম', accessibility:'♿ সবার জন্য', budget:'💸 বাজেট', sustainability:'♻️ স্থায়িত্ব', climate:'🌦️ আবহাওয়া', cultural:'🪔 সাংস্কৃতিক', confidence:'✨ আত্মবিশ্বাস' }, agentwhy: { sustain:'আবার পরা যায়', climate_ok:'কাপড় ঋতুর উপযোগী', cultural_ok:'উপলক্ষকে সম্মান করে' },
      chrome: { experts:'৯ বিশেষজ্ঞের মত', open:'(খুলুন)', trend:'📈 ট্রেন্ড (শুধু তথ্য): ', whyq:'🎓 কেন, Chitti? (শিখুন)', why:'কেন', benefits:'সুবিধা', tradeoffs:'আপস', alts:'বিকল্প', free:'✅ বিনামূল্যে (আপনার আলমারি থেকে · ₹0)', cheap:'💸 সস্তা উপায়', premium:'⭐ প্রিমিয়াম', conf:'আত্মবিশ্বাস', checks_pass:'যাচাই পাস' },
      conf: { occasion:'উপলক্ষ', color:'রঙ', weather:'আবহাওয়া', budget:'বাজেট', accessibility:'সবার জন্য' },
      judge: { cultural:'সাংস্কৃতিক', weather:'আবহাওয়া', age:'বয়স', accessibility:'প্রবেশযোগ্যতা', funeral_bright:'উজ্জ্বল/লাল উৎসবের মতো — শোকে সাদা বা নরম রঙ', wedding_white:'বিয়েতে পুরো সাদা অনেক সম্প্রদায়ে শোকের মতো লাগতে পারে — নিশ্চিত করুন', season_mismatch:'কাপড় অন্য ঋতুর — স্তর ঠিক করুন', senior_footwear:'আরাম ও নিরাপত্তার জন্য পিছল-রোধী, সহজ জুতো ভালো', child_safety:'শিশুর জন্য আরামদায়ক ও নিরাপদ রাখুন', easy_fasten:'নিজে পরার জন্য magnetic/velcro/front-open ভালো' },
      tmpl: { reads:'এটি {occ} লাগছে (formality {band}/5)। রঙ: {harm}।', wear:'আপনি পরতে পারেন: {items}। এটি {occ}-এর জন্য ঠিক আছে।', built:'{n} পোশাক আপনার নিজের জামাকাপড় থেকে — ₹0', made:'আপনার আলমারি থেকে {n} পোশাক তৈরি করেছি', just:'✅ {occ}-এর জন্য ঠিক', over:'⬆️ {occ}-এর জন্য একটু বেশি ফর্মাল', under:'⬇️ {occ}-এর জন্য একটু ক্যাজুয়াল', overall:'মোট {n}/10' },
    },
    te: {
      occ: { casual:'ప్రతిరోజూ', 'smart-casual':'స్మార్ట్-క్యాజువల్', 'business-casual':'బిజినెస్-క్యాజువల్', formal:'ఫార్మల్', festive:'పండుగ', wedding:'వివాహం', office:'కార్యాలయం', interview:'ఇంటర్వ్యూ', college:'కళాశాల', religious:'మత', date:'డేట్ నైట్', travel:'ప్రయాణం', funeral:'సంతాపం', family:'కుటుంబ వేడుక' },
      harm: { single:'ఒకే రంగు — ఎప్పుడూ సురక్షితం', 'neutral-anchored':'ఒక తటస్థ రంగు మిగతావాటిని మెరిపిస్తుంది — శుభ్రం', monochrome:'ఒకే రంగు కుటుంబం పొందికగా ఉంటుంది', 'two-tone':'రెండు రంగు కుటుంబాలు, సమతుల్య వ్యత్యాసం', mixed:'చాలా రంగులు — ఒక తటస్థ రంగు శాంతపరుస్తుంది', competing:'రెండు ప్రకాశవంతమైన రంగులు పోటీపడతాయి — ఒక తటస్థ రంగు జోడించండి' },
      agent: { fashion:'👗 స్టైల్', color:'🎨 రంగు', occasion:'🎉 సందర్భం', comfort:'😌 సౌకర్యం', accessibility:'♿ అందరికీ', budget:'💸 బడ్జెట్', sustainability:'♻️ స్థిరత్వం', climate:'🌦️ వాతావరణం', cultural:'🪔 సాంస్కృతిక', confidence:'✨ నమ్మకం' }, agentwhy: { sustain:'మళ్లీ ధరించవచ్చు', climate_ok:'వస్త్రం కాలానికి సరిపోతుంది', cultural_ok:'సందర్భాన్ని గౌరవిస్తుంది' },
      chrome: { experts:'9 నిపుణుల అభిప్రాయం', open:'(తెరువు)', trend:'📈 ట్రెండ్ (సమాచారం మాత్రమే): ', whyq:'🎓 ఎందుకు, Chitti? (నేర్చుకో)', why:'ఎందుకు', benefits:'ప్రయోజనాలు', tradeoffs:'రాజీలు', alts:'ప్రత్యామ్నాయాలు', free:'✅ ఉచితం (మీ అలమారా నుండి · ₹0)', cheap:'💸 చౌక మార్గం', premium:'⭐ ప్రీమియం', conf:'నమ్మకం', checks_pass:'తనిఖీలు సరి' },
      conf: { occasion:'సందర్భం', color:'రంగు', weather:'వాతావరణం', budget:'బడ్జెట్', accessibility:'అందరికీ' },
      judge: { cultural:'సాంస్కృతిక', weather:'వాతావరణం', age:'వయస్సు', accessibility:'ప్రాప్యత', funeral_bright:'ప్రకాశవంతమైన/ఎరుపు పండుగలా కనిపిస్తుంది — సంతాపానికి తెలుపు లేదా మృదు రంగు', wedding_white:'వివాహంలో పూర్తి తెలుపు చాలా వర్గాల్లో సంతాపంలా కనిపించవచ్చు — నిర్ధారించండి', season_mismatch:'వస్త్రం వేరే కాలానికి సంబంధించినది — పొరలను సర్దుబాటు చేయండి', senior_footwear:'సౌకర్యం, భద్రత కోసం జారని, సులభంగా వేసుకునే పాదరక్షలు మంచివి', child_safety:'పిల్లలకు సౌకర్యవంతంగా, సురక్షితంగా ఉంచండి', easy_fasten:'స్వయంగా వేసుకోవడానికి magnetic/velcro/front-open మంచిది' },
      tmpl: { reads:'ఇది {occ} లా కనిపిస్తుంది (formality {band}/5). రంగు: {harm}.', wear:'మీరు ధరించవచ్చు: {items}. ఇది {occ}కు సరైనది.', built:'{n} దుస్తులు మీ సొంత దుస్తుల నుండి — ₹0', made:'మీ అలమారా నుండి {n} దుస్తులను తయారు చేశాను', just:'✅ {occ}కు సరైనది', over:'⬆️ {occ}కు కొంచెం ఎక్కువ ఫార్మల్', under:'⬇️ {occ}కు కొంచెం క్యాజువల్', overall:'మొత్తం {n}/10' },
    },
    mr: {
      occ: { casual:'रोज', 'smart-casual':'स्मार्ट-कॅज्युअल', 'business-casual':'बिझनेस-कॅज्युअल', formal:'फॉर्मल', festive:'सणाचा', wedding:'लग्न', office:'कार्यालय', interview:'मुलाखत', college:'महाविद्यालय', religious:'धार्मिक', date:'डेट नाइट', travel:'प्रवास', funeral:'शोक', family:'कौटुंबिक समारंभ' },
      harm: { single:'एक रंग — नेहमी सुरक्षित', 'neutral-anchored':'एक तटस्थ रंग बाकीच्यांना उठाव देतो — स्वच्छ', monochrome:'एकच रंग-कुटुंब सुसंगत दिसते', 'two-tone':'दोन रंग-कुटुंबे, संतुलित विरोधाभास', mixed:'अनेक रंग — एक तटस्थ रंग शांत करेल', competing:'दोन भडक रंग भिडतात — एक तटस्थ रंग जोडा' },
      agent: { fashion:'👗 स्टाईल', color:'🎨 रंग', occasion:'🎉 प्रसंग', comfort:'😌 आराम', accessibility:'♿ सर्वांसाठी', budget:'💸 बजेट', sustainability:'♻️ शाश्वतता', climate:'🌦️ हवामान', cultural:'🪔 सांस्कृतिक', confidence:'✨ आत्मविश्वास' }, agentwhy: { sustain:'पुन्हा घालता येते', climate_ok:'कापड हंगामास योग्य', cultural_ok:'प्रसंगाचा आदर करते' },
      chrome: { experts:'9 तज्ज्ञांचे मत', open:'(उघडा)', trend:'📈 ट्रेंड (फक्त माहिती): ', whyq:'🎓 का, Chitti? (शिका)', why:'का', benefits:'फायदे', tradeoffs:'तडजोडी', alts:'पर्याय', free:'✅ मोफत (तुमच्या अलमारीतून · ₹0)', cheap:'💸 स्वस्त मार्ग', premium:'⭐ प्रीमियम', conf:'आत्मविश्वास', checks_pass:'तपासण्या पास' },
      conf: { occasion:'प्रसंग', color:'रंग', weather:'हवामान', budget:'बजेट', accessibility:'सर्वांसाठी' },
      judge: { cultural:'सांस्कृतिक', weather:'हवामान', age:'वय', accessibility:'सुलभता', funeral_bright:'भडक/लाल रंग सणासारखा दिसतो — शोकात पांढरा किंवा मऊ रंग', wedding_white:'लग्नात पूर्ण पांढरा अनेक समाजांत शोकासारखा वाटू शकतो — खात्री करा', season_mismatch:'कापड दुसऱ्या हंगामाचे आहे — थर समायोजित करा', senior_footwear:'आराम व सुरक्षेसाठी न घसरणारे, सोपे पादत्राण चांगले', child_safety:'मुलासाठी आरामदायी व सुरक्षित ठेवा', easy_fasten:'स्वतः घालण्यासाठी magnetic/velcro/front-open चांगले' },
      tmpl: { reads:'हे {occ} वाटते (formality {band}/5). रंग: {harm}.', wear:'तुम्ही घालू शकता: {items}. हे {occ}साठी योग्य आहे.', built:'{n} पोशाक तुमच्याच कपड्यांमधून — ₹0', made:'तुमच्या अलमारीतून {n} पोशाक तयार केले', just:'✅ {occ}साठी योग्य', over:'⬆️ {occ}साठी थोडे जास्त फॉर्मल', under:'⬇️ {occ}साठी थोडे कॅज्युअल', overall:'एकूण {n}/10' },
    },
    gu: {
      occ: { casual:'રોજ', 'smart-casual':'સ્માર્ટ-કેઝ્યુઅલ', 'business-casual':'બિઝનેસ-કેઝ્યુઅલ', formal:'ફોર્મલ', festive:'તહેવારી', wedding:'લગ્ન', office:'ઓફિસ', interview:'ઇન્ટરવ્યૂ', college:'કૉલેજ', religious:'ધાર્મિક', date:'ડેટ નાઇટ', travel:'મુસાફરી', funeral:'શોક', family:'કૌટુંબિક પ્રસંગ' },
      harm: { single:'એક રંગ — હંમેશા સલામત', 'neutral-anchored':'એક તટસ્થ રંગ બાકીનાને નિખારે છે — સ્વચ્છ', monochrome:'એક જ રંગ-કુટુંબ સુસંગત લાગે', 'two-tone':'બે રંગ-કુટુંબ, સંતુલિત વિરોધાભાસ', mixed:'ઘણા રંગ — એક તટસ્થ રંગ શાંત કરશે', competing:'બે ભડક રંગ ટકરાય — એક તટસ્થ ઉમેરો' },
      agent: { fashion:'👗 સ્ટાઇલ', color:'🎨 રંગ', occasion:'🎉 પ્રસંગ', comfort:'😌 આરામ', accessibility:'♿ બધા માટે', budget:'💸 બજેટ', sustainability:'♻️ ટકાઉપણું', climate:'🌦️ હવામાન', cultural:'🪔 સાંસ્કૃતિક', confidence:'✨ આત્મવિશ્વાસ' }, agentwhy: { sustain:'ફરી પહેરી શકાય', climate_ok:'કાપડ ઋતુને અનુકૂળ', cultural_ok:'પ્રસંગનું સન્માન કરે' },
      chrome: { experts:'9 નિષ્ણાતોનો મત', open:'(ખોલો)', trend:'📈 ટ્રેન્ડ (ફક્ત માહિતી): ', whyq:'🎓 શા માટે, Chitti? (શીખો)', why:'શા માટે', benefits:'ફાયદા', tradeoffs:'સમાધાન', alts:'વિકલ્પ', free:'✅ મફત (તમારી અલમારીમાંથી · ₹0)', cheap:'💸 સસ્તો રસ્તો', premium:'⭐ પ્રીમિયમ', conf:'આત્મવિશ્વાસ', checks_pass:'તપાસ પાસ' },
      conf: { occasion:'પ્રસંગ', color:'રંગ', weather:'હવામાન', budget:'બજેટ', accessibility:'બધા માટે' },
      judge: { cultural:'સાંસ્કૃતિક', weather:'હવામાન', age:'ઉંમર', accessibility:'સુલભતા', funeral_bright:'ભડક/લાલ રંગ તહેવાર જેવો લાગે — શોકમાં સફેદ કે હળવો રંગ', wedding_white:'લગ્નમાં આખો સફેદ ઘણા સમુદાયોમાં શોક જેવો લાગે — ખાતરી કરો', season_mismatch:'કાપડ બીજી ઋતુનું છે — સ્તર સમાયોજિત કરો', senior_footwear:'આરામ અને સલામતી માટે ન લપસે તેવા, સરળ પગરખાં સારા', child_safety:'બાળક માટે આરામદાયક અને સલામત રાખો', easy_fasten:'જાતે પહેરવા magnetic/velcro/front-open સારું' },
      tmpl: { reads:'આ {occ} લાગે છે (formality {band}/5). રંગ: {harm}.', wear:'તમે પહેરી શકો: {items}. આ {occ} માટે યોગ્ય છે.', built:'{n} પોશાક તમારા પોતાના કપડાંમાંથી — ₹0', made:'તમારી અલમારીમાંથી {n} પોશાક બનાવ્યા', just:'✅ {occ} માટે યોગ્ય', over:'⬆️ {occ} માટે થોડું વધારે ફોર્મલ', under:'⬇️ {occ} માટે થોડું કેઝ્યુઅલ', overall:'કુલ {n}/10' },
    },
    kn: {
      occ: { casual:'ಪ್ರತಿದಿನ', 'smart-casual':'ಸ್ಮಾರ್ಟ್-ಕ್ಯಾಶುಯಲ್', 'business-casual':'ಬಿಸಿನೆಸ್-ಕ್ಯಾಶುಯಲ್', formal:'ಫಾರ್ಮಲ್', festive:'ಹಬ್ಬದ', wedding:'ಮದುವೆ', office:'ಕಚೇರಿ', interview:'ಸಂದರ್ಶನ', college:'ಕಾಲೇಜು', religious:'ಧಾರ್ಮಿಕ', date:'ಡೇಟ್ ನೈಟ್', travel:'ಪ್ರಯಾಣ', funeral:'ಶೋಕ', family:'ಕೌಟುಂಬಿಕ ಸಮಾರಂಭ' },
      harm: { single:'ಒಂದೇ ಬಣ್ಣ — ಯಾವಾಗಲೂ ಸುರಕ್ಷಿತ', 'neutral-anchored':'ಒಂದು ತಟಸ್ಥ ಬಣ್ಣ ಉಳಿದವನ್ನು ಹೊಳೆಯಿಸುತ್ತದೆ — ಸ್ವಚ್ಛ', monochrome:'ಒಂದೇ ಬಣ್ಣ ಕುಟುಂಬ ಹೊಂದಿಕೆಯಾಗಿದೆ', 'two-tone':'ಎರಡು ಬಣ್ಣ ಕುಟುಂಬಗಳು, ಸಮತೋಲಿತ ವ್ಯತ್ಯಾಸ', mixed:'ಹಲವು ಬಣ್ಣಗಳು — ಒಂದು ತಟಸ್ಥ ಬಣ್ಣ ಶಾಂತಗೊಳಿಸುತ್ತದೆ', competing:'ಎರಡು ಪ್ರಕಾಶಮಾನ ಬಣ್ಣಗಳು ಸ್ಪರ್ಧಿಸುತ್ತವೆ — ಒಂದು ತಟಸ್ಥ ಸೇರಿಸಿ' },
      agent: { fashion:'👗 ಸ್ಟೈಲ್', color:'🎨 ಬಣ್ಣ', occasion:'🎉 ಸಂದರ್ಭ', comfort:'😌 ಸೌಕರ್ಯ', accessibility:'♿ ಎಲ್ಲರಿಗೂ', budget:'💸 ಬಜೆಟ್', sustainability:'♻️ ಸುಸ್ಥಿರತೆ', climate:'🌦️ ಹವಾಮಾನ', cultural:'🪔 ಸಾಂಸ್ಕೃತಿಕ', confidence:'✨ ಆತ್ಮವಿಶ್ವಾಸ' }, agentwhy: { sustain:'ಮತ್ತೆ ಧರಿಸಬಹುದು', climate_ok:'ಬಟ್ಟೆ ಋತುವಿಗೆ ಸೂಕ್ತ', cultural_ok:'ಸಂದರ್ಭವನ್ನು ಗೌರವಿಸುತ್ತದೆ' },
      chrome: { experts:'9 ತಜ್ಞರ ಅಭಿಪ್ರಾಯ', open:'(ತೆರೆ)', trend:'📈 ಟ್ರೆಂಡ್ (ಮಾಹಿತಿ ಮಾತ್ರ): ', whyq:'🎓 ಏಕೆ, Chitti? (ಕಲಿ)', why:'ಏಕೆ', benefits:'ಪ್ರಯೋಜನ', tradeoffs:'ರಾಜಿ', alts:'ಪರ್ಯಾಯ', free:'✅ ಉಚಿತ (ನಿಮ್ಮ ಅಲಮಾರಿಯಿಂದ · ₹0)', cheap:'💸 ಅಗ್ಗದ ಮಾರ್ಗ', premium:'⭐ ಪ್ರೀಮಿಯಂ', conf:'ಆತ್ಮವಿಶ್ವಾಸ', checks_pass:'ಪರಿಶೀಲನೆ ಪಾಸ್' },
      conf: { occasion:'ಸಂದರ್ಭ', color:'ಬಣ್ಣ', weather:'ಹವಾಮಾನ', budget:'ಬಜೆಟ್', accessibility:'ಎಲ್ಲರಿಗೂ' },
      judge: { cultural:'ಸಾಂಸ್ಕೃತಿಕ', weather:'ಹವಾಮಾನ', age:'ವಯಸ್ಸು', accessibility:'ಪ್ರವೇಶ', funeral_bright:'ಪ್ರಕಾಶಮಾನ/ಕೆಂಪು ಹಬ್ಬದಂತೆ ಕಾಣುತ್ತದೆ — ಶೋಕಕ್ಕೆ ಬಿಳಿ ಅಥವಾ ಮೃದು ಬಣ್ಣ', wedding_white:'ಮದುವೆಯಲ್ಲಿ ಪೂರ್ಣ ಬಿಳಿ ಹಲವು ಸಮುದಾಯಗಳಲ್ಲಿ ಶೋಕದಂತೆ ಕಾಣಬಹುದು — ಖಚಿತಪಡಿಸಿ', season_mismatch:'ಬಟ್ಟೆ ಬೇರೆ ಋತುವಿನದು — ಪದರಗಳನ್ನು ಸರಿಹೊಂದಿಸಿ', senior_footwear:'ಸೌಕರ್ಯ, ಸುರಕ್ಷತೆಗೆ ಜಾರದ, ಸುಲಭ ಪಾದರಕ್ಷೆ ಒಳ್ಳೆಯದು', child_safety:'ಮಗುವಿಗೆ ಆರಾಮ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿರಿಸಿ', easy_fasten:'ಸ್ವತಃ ಧರಿಸಲು magnetic/velcro/front-open ಒಳ್ಳೆಯದು' },
      tmpl: { reads:'ಇದು {occ} ಎಂದು ಕಾಣುತ್ತದೆ (formality {band}/5). ಬಣ್ಣ: {harm}.', wear:'ನೀವು ಧರಿಸಬಹುದು: {items}. ಇದು {occ}ಗೆ ಸರಿಯಾಗಿದೆ.', built:'{n} ಉಡುಗೆಗಳು ನಿಮ್ಮ ಸ್ವಂತ ಬಟ್ಟೆಗಳಿಂದ — ₹0', made:'ನಿಮ್ಮ ಅಲಮಾರಿಯಿಂದ {n} ಉಡುಗೆಗಳನ್ನು ತಯಾರಿಸಿದೆ', just:'✅ {occ}ಗೆ ಸರಿ', over:'⬆️ {occ}ಗೆ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಫಾರ್ಮಲ್', under:'⬇️ {occ}ಗೆ ಸ್ವಲ್ಪ ಕ್ಯಾಶುಯಲ್', overall:'ಒಟ್ಟು {n}/10' },
    },
    ml: {
      occ: { casual:'ദിവസവും', 'smart-casual':'സ്മാർട്ട്-കാഷ്വൽ', 'business-casual':'ബിസിനസ്-കാഷ്വൽ', formal:'ഫോർമൽ', festive:'ഉത്സവ', wedding:'വിവാഹം', office:'ഓഫീസ്', interview:'ഇന്റർവ്യൂ', college:'കോളേജ്', religious:'മത', date:'ഡേറ്റ് നൈറ്റ്', travel:'യാത്ര', funeral:'ദുഃഖാചരണം', family:'കുടുംബ ചടങ്ങ്' },
      harm: { single:'ഒരേ നിറം — എപ്പോഴും സുരക്ഷിതം', 'neutral-anchored':'ഒരു നിഷ്പക്ഷ നിറം ബാക്കിയുള്ളവയെ തിളക്കുന്നു — വൃത്തിയുള്ളത്', monochrome:'ഒരേ നിറ കുടുംബം യോജിച്ചതായി തോന്നുന്നു', 'two-tone':'രണ്ട് നിറ കുടുംബങ്ങൾ, സന്തുലിത വൈരുദ്ധ്യം', mixed:'പല നിറങ്ങൾ — ഒരു നിഷ്പക്ഷ നിറം ശാന്തമാക്കും', competing:'രണ്ട് തിളക്കമുള്ള നിറങ്ങൾ മത്സരിക്കുന്നു — ഒരു നിഷ്പക്ഷ നിറം ചേർക്കുക' },
      agent: { fashion:'👗 സ്റ്റൈൽ', color:'🎨 നിറം', occasion:'🎉 അവസരം', comfort:'😌 സൗകര്യം', accessibility:'♿ എല്ലാവർക്കും', budget:'💸 ബജറ്റ്', sustainability:'♻️ സുസ്ഥിരത', climate:'🌦️ കാലാവസ്ഥ', cultural:'🪔 സാംസ്കാരിക', confidence:'✨ ആത്മവിശ്വാസം' }, agentwhy: { sustain:'വീണ്ടും ധരിക്കാം', climate_ok:'വസ്ത്രം ഋതുവിന് അനുയോജ്യം', cultural_ok:'അവസരത്തെ മാനിക്കുന്നു' },
      chrome: { experts:'9 വിദഗ്ധരുടെ അഭിപ്രായം', open:'(തുറക്കൂ)', trend:'📈 ട്രെൻഡ് (വിവരം മാത്രം): ', whyq:'🎓 എന്തുകൊണ്ട്, Chitti? (പഠിക്കൂ)', why:'എന്തുകൊണ്ട്', benefits:'നേട്ടങ്ങൾ', tradeoffs:'വിട്ടുവീഴ്ചകൾ', alts:'ബദലുകൾ', free:'✅ സൗജന്യം (നിങ്ങളുടെ അലമാരയിൽ നിന്ന് · ₹0)', cheap:'💸 വിലകുറഞ്ഞ വഴി', premium:'⭐ പ്രീമിയം', conf:'ആത്മവിശ്വാസം', checks_pass:'പരിശോധനകൾ പാസ്' },
      conf: { occasion:'അവസരം', color:'നിറം', weather:'കാലാവസ്ഥ', budget:'ബജറ്റ്', accessibility:'എല്ലാവർക്കും' },
      judge: { cultural:'സാംസ്കാരിക', weather:'കാലാവസ്ഥ', age:'പ്രായം', accessibility:'പ്രവേശനക്ഷമത', funeral_bright:'തിളക്കമുള്ള/ചുവപ്പ് ഉത്സവം പോലെ തോന്നുന്നു — ദുഃഖത്തിന് വെള്ള അല്ലെങ്കിൽ മൃദു നിറം', wedding_white:'വിവാഹത്തിൽ പൂർണ വെള്ള പല സമൂഹങ്ങളിലും ദുഃഖം പോലെ തോന്നാം — സ്ഥിരീകരിക്കുക', season_mismatch:'വസ്ത്രം മറ്റൊരു ഋതുവിന്റേതാണ് — പാളികൾ ക്രമീകരിക്കുക', senior_footwear:'സൗകര്യത്തിനും സുരക്ഷയ്ക്കും വഴുതാത്ത, എളുപ്പം ധരിക്കാവുന്ന പാദരക്ഷ നല്ലത്', child_safety:'കുട്ടിക്ക് സൗകര്യപ്രദവും സുരക്ഷിതവുമായി സൂക്ഷിക്കുക', easy_fasten:'സ്വയം ധരിക്കാൻ magnetic/velcro/front-open നല്ലത്' },
      tmpl: { reads:'ഇത് {occ} പോലെ തോന്നുന്നു (formality {band}/5). നിറം: {harm}.', wear:'നിങ്ങൾക്ക് ധരിക്കാം: {items}. ഇത് {occ}-ന് അനുയോജ്യമാണ്.', built:'{n} വസ്ത്രങ്ങൾ നിങ്ങളുടെ സ്വന്തം വസ്ത്രങ്ങളിൽ നിന്ന് — ₹0', made:'നിങ്ങളുടെ അലമാരയിൽ നിന്ന് {n} വസ്ത്രങ്ങൾ ഉണ്ടാക്കി', just:'✅ {occ}-ന് ശരി', over:'⬆️ {occ}-ന് അൽപം കൂടുതൽ ഫോർമൽ', under:'⬇️ {occ}-ന് അൽപം കാഷ്വൽ', overall:'ആകെ {n}/10' },
    },
  };
  var MORE = {
    en: { add_first:'Add clothes to your Almari first.', need_more:'Add a top and a bottom.', gap_bottom:'more bottoms unlock more outfits', gap_footwear:'add footwear', total:'items', outfits:'outfits', gaps:'Gaps', rare:'not worn in 6 months', best_buy:'Best-value buy', items:'items', go:'Ready — go!', roi:'{item} unlocks {n} new outfits', pack_for:'Packed for {days} days', pack_why:'{n} items → {c} mix-and-match outfits', per_wear:'per wear', cpw:'Cost per wear', reuse_ladder:'reuse · mix · repair · borrow · rent first', last_option:'last option' },
    hi: { add_first:'पहले अलमारी में कपड़े जोड़ें।', need_more:'एक ऊपर और एक नीचे का कपड़ा जोड़ें।', gap_bottom:'और नीचे के कपड़े = ज़्यादा पहनावे', gap_footwear:'जूते जोड़ें', total:'चीज़ें', outfits:'पहनावे', gaps:'कमी', rare:'6 महीने से नहीं पहने', best_buy:'सबसे फ़ायदेमंद खरीद', items:'चीज़ें', go:'तैयार — चलिए!', roi:'{item} से {n} नए पहनावे खुलते हैं', pack_for:'{days} दिन के लिए पैक', pack_why:'{n} चीज़ें → {c} mix-and-match पहनावे', per_wear:'प्रति बार', cpw:'प्रति बार लागत', reuse_ladder:'फिर पहनें · जोड़ी · मरम्मत · उधार · किराया — पहले', last_option:'आख़िरी विकल्प' },
    ta: { add_first:'முதலில் அலமாரியில் ஆடைகளைச் சேர்க்கவும்.', need_more:'ஒரு மேலாடை, ஒரு கீழாடை சேர்க்கவும்.', gap_bottom:'மேலும் கீழாடைகள் = அதிக உடைகள்', gap_footwear:'காலணி சேர்க்கவும்', total:'பொருட்கள்', outfits:'உடைகள்', gaps:'குறை', rare:'6 மாதமாக அணியவில்லை', best_buy:'மிகப் பயனுள்ள வாங்குதல்', items:'பொருட்கள்', go:'தயார் — செல்லுங்கள்!', roi:'{item} {n} புதிய உடைகளைத் திறக்கிறது', pack_for:'{days} நாட்களுக்குப் பேக்', pack_why:'{n} பொருட்கள் → {c} உடைகள்' },
    bn: { add_first:'প্রথমে আলমারিতে জামাকাপড় যোগ করুন।', need_more:'একটি উপরের ও একটি নিচের পোশাক যোগ করুন।', gap_bottom:'আরও নিচের পোশাক = বেশি পোশাক', gap_footwear:'জুতো যোগ করুন', total:'জিনিস', outfits:'পোশাক', gaps:'ঘাটতি', rare:'৬ মাস ধরে পরা হয়নি', best_buy:'সবচেয়ে লাভজনক কেনাকাটা', items:'জিনিস', go:'প্রস্তুত — চলুন!', roi:'{item} {n}টি নতুন পোশাক খোলে', pack_for:'{days} দিনের জন্য প্যাক', pack_why:'{n} জিনিস → {c} পোশাক' },
    te: { add_first:'ముందుగా అలమారాలో దుస్తులు జోడించండి.', need_more:'ఒక పైదుస్తు, ఒక కింది దుస్తు జోడించండి.', gap_bottom:'మరిన్ని కింది దుస్తులు = ఎక్కువ దుస్తులు', gap_footwear:'పాదరక్షలు జోడించండి', total:'వస్తువులు', outfits:'దుస్తులు', gaps:'లోటు', rare:'6 నెలలుగా ధరించలేదు', best_buy:'అత్యధిక విలువైన కొనుగోలు', items:'వస్తువులు', go:'సిద్ధం — వెళ్ళండి!', roi:'{item} {n} కొత్త దుస్తులను తెరుస్తుంది', pack_for:'{days} రోజులకు ప్యాక్', pack_why:'{n} వస్తువులు → {c} దుస్తులు' },
    mr: { add_first:'आधी अलमारीत कपडे जोडा.', need_more:'एक वरचा आणि एक खालचा कपडा जोडा.', gap_bottom:'अधिक खालचे कपडे = जास्त पोशाक', gap_footwear:'पादत्राण जोडा', total:'वस्तू', outfits:'पोशाक', gaps:'कमतरता', rare:'6 महिने घातले नाहीत', best_buy:'सर्वात फायदेशीर खरेदी', items:'वस्तू', go:'तयार — चला!', roi:'{item} {n} नवे पोशाक उघडते', pack_for:'{days} दिवसांसाठी पॅक', pack_why:'{n} वस्तू → {c} पोशाक' },
    gu: { add_first:'પહેલા અલમારીમાં કપડાં ઉમેરો.', need_more:'એક ઉપરનું અને એક નીચેનું કપડું ઉમેરો.', gap_bottom:'વધુ નીચેના કપડાં = વધુ પોશાક', gap_footwear:'પગરખાં ઉમેરો', total:'વસ્તુઓ', outfits:'પોશાક', gaps:'ઉણપ', rare:'6 મહિનાથી પહેર્યા નથી', best_buy:'સૌથી ફાયદાકારક ખરીદી', items:'વસ્તુઓ', go:'તૈયાર — ચાલો!', roi:'{item} {n} નવા પોશાક ખોલે', pack_for:'{days} દિવસ માટે પૅક', pack_why:'{n} વસ્તુઓ → {c} પોશાક' },
    kn: { add_first:'ಮೊದಲು ಅಲಮಾರಿಯಲ್ಲಿ ಬಟ್ಟೆ ಸೇರಿಸಿ.', need_more:'ಒಂದು ಮೇಲಿನ, ಒಂದು ಕೆಳಗಿನ ಬಟ್ಟೆ ಸೇರಿಸಿ.', gap_bottom:'ಹೆಚ್ಚು ಕೆಳಗಿನ ಬಟ್ಟೆ = ಹೆಚ್ಚು ಉಡುಗೆ', gap_footwear:'ಪಾದರಕ್ಷೆ ಸೇರಿಸಿ', total:'ವಸ್ತುಗಳು', outfits:'ಉಡುಗೆಗಳು', gaps:'ಕೊರತೆ', rare:'6 ತಿಂಗಳಿಂದ ಧರಿಸಿಲ್ಲ', best_buy:'ಅತ್ಯಂತ ಲಾಭದಾಯಕ ಖರೀದಿ', items:'ವಸ್ತುಗಳು', go:'ಸಿದ್ಧ — ಹೋಗಿ!', roi:'{item} {n} ಹೊಸ ಉಡುಗೆಗಳನ್ನು ತೆರೆಯುತ್ತದೆ', pack_for:'{days} ದಿನಗಳಿಗೆ ಪ್ಯಾಕ್', pack_why:'{n} ವಸ್ತುಗಳು → {c} ಉಡುಗೆಗಳು' },
    ml: { add_first:'ആദ്യം അലമാരയിൽ വസ്ത്രങ്ങൾ ചേർക്കൂ.', need_more:'ഒരു മേൽവസ്ത്രവും ഒരു കീഴ്വസ്ത്രവും ചേർക്കൂ.', gap_bottom:'കൂടുതൽ കീഴ്വസ്ത്രം = കൂടുതൽ വസ്ത്രങ്ങൾ', gap_footwear:'പാദരക്ഷ ചേർക്കൂ', total:'വസ്തുക്കൾ', outfits:'വസ്ത്രങ്ങൾ', gaps:'കുറവ്', rare:'6 മാസമായി ധരിച്ചിട്ടില്ല', best_buy:'ഏറ്റവും ലാഭകരമായ വാങ്ങൽ', items:'വസ്തുക്കൾ', go:'തയ്യാർ — പോകൂ!', roi:'{item} {n} പുതിയ വസ്ത്രങ്ങൾ തുറക്കുന്നു', pack_for:'{days} ദിവസത്തേക്ക് പായ്ക്ക്', pack_why:'{n} വസ്തുക്കൾ → {c} വസ്ത്രങ്ങൾ' },
  };
  function more(key, vars, L) { L = L || lang(); var s = (MORE[L] || MORE.en)[key] || MORE.en[key] || key; for (var k in (vars || {})) s = s.split('{' + k + '}').join(vars[k]); return s; }
  function lang() { try { return localStorage.getItem('chitti_vaani_lang') || 'hi'; } catch (e) { return 'hi'; } }
  function bag(L) { return D[L] || D.en; }
  function t(group, key, L) { L = L || lang(); var g = bag(L)[group] || {}; return g[key] || (D.en[group] || {})[key] || key; }
  function tmpl(key, vars, L) { L = L || lang(); var s = (bag(L).tmpl || {})[key] || (D.en.tmpl || {})[key] || ''; for (var k in (vars || {})) s = s.split('{' + k + '}').join(vars[k]); return s; }
  window.FashionDyn = {
    occ: function (code, L) { return t('occ', code, L); },
    harm: function (code, L) { return t('harm', code, L); },
    agent: function (code, L) { return t('agent', code, L); },
    agentWhy: function (code, L) { return t('agentwhy', code, L); },
    chrome: function (code, L) { return t('chrome', code, L); },
    conf: function (code, L) { return t('conf', code, L); },
    judgeAxis: function (code, L) { return t('judge', code, L); },
    judgeMsg: function (code, L) { return t('judge', code, L); },
    tmpl: tmpl,
    more: more,
    // CFOS v2.1 dynamic-output accessors (en+hi full; cousins fall back to en via t())
    repair: function (code, L) { return t('repair', code, L); },
    wedding: function (code, L) { return t('wedding', code, L); },
    week: function (code, L) { return t('week', code, L); },
    lang: lang,
  };
})();
