"""
models/article.py
-----------------
One article = one ingested news item from any RSS source.
Natural key: link URL (unique). Hash falls back when an outlet
publishes the same article under multiple URLs.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import Column, DateTime, Float, Integer, String, Text, Index

from database import Base
from models._schema import TABLE_KW


class Article(Base):
    __tablename__ = "articles"

    id = Column(Integer, primary_key=True, index=True)

    # ── Identity ──
    title = Column(String(500), nullable=False)
    title_hash = Column(String(64), index=True, nullable=True)  # for cross-source dedup
    link = Column(String(900), unique=True, index=True, nullable=False)
    summary = Column(Text, nullable=True)
    content = Column(Text, nullable=True)             # full text where available

    # ── Source metadata ──
    source_slug = Column(String(60), index=True, nullable=False)   # e.g. "toi", "bhaskar", "moneycontrol"
    source_name = Column(String(120), nullable=True)
    source_url = Column(String(300), nullable=True)
    image_url = Column(String(500), nullable=True)
    author = Column(String(160), nullable=True)

    # ── Targeting (state + language + category) ──
    state = Column(String(40), index=True, nullable=False, default="india")  # india / mp / mh / ka / tn / ...
    language = Column(String(8),  index=True, nullable=False, default="en")  # en / hi / bn / te / ta / mr / kn
    category = Column(String(32), index=True, nullable=False, default="national")
    # category: national / state / business / tech / sports / entertainment / politics / science / breaking

    # ── Editorial ──
    is_breaking = Column(Integer, nullable=False, default=0)        # 1 = breaking news
    sentiment = Column(String(8), nullable=True)                    # pos / neg / neu (future)
    importance = Column(Integer, nullable=False, default=5)         # 1–10

    # ── Chitti's Insight (Sire 2026-06-04, priority #2) ──
    # One-sentence editorial line generated by services/news_insight.py.
    # Pre-computed asynchronously by the insight_sweep scheduler so the
    # card ships it instantly with no LLM round-trip at render time.
    # NULL = no insight yet OR the validator rejected the LLM output
    # (URLs, unsourced quotes, unsourced named entities…). The frontend
    # hides the line entirely when NULL — never shows a placeholder.
    chitti_insight = Column(Text, nullable=True)
    chitti_insight_at = Column(DateTime, nullable=True)
    # Audit field — when the validator rejects, the reason is stored.
    # NULL when no attempt has been made yet OR the insight was accepted.
    chitti_insight_reject = Column(String(64), nullable=True)

    # SOP-001 step 5 — Context Agent: "why this matters" + affected-group note.
    # ≤ 140 chars, declarative present-tense, one short sentence. NULL = not
    # generated yet or rejected by validator. Frontend hides line when NULL.
    why_this_matters = Column(Text, nullable=True)
    why_this_matters_at = Column(DateTime, nullable=True)
    why_this_matters_reject = Column(String(64), nullable=True)

    # SOP-001 step 6 — Action Agent: "what to watch for" or "what to do next".
    # ≤ 140 chars, imperative voice. NULL = not generated yet or rejected.
    # Frontend hides line when NULL.
    action_plan = Column(Text, nullable=True)
    action_plan_at = Column(DateTime, nullable=True)
    action_plan_reject = Column(String(64), nullable=True)

    # ── Time ──
    published_at = Column(DateTime, index=True, nullable=True)
    fetched_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    __table_args__ = (
        Index("ix_articles_state_lang_cat", "state", "language", "category"),
        Index("ix_articles_published_recent", "published_at"),
        TABLE_KW,
    )
