"""
models/breaking_alert.py
------------------------
Breaking news ribbon entries — surfaced to all users until dismissed
or expired. Generated by the breaking-news watcher when ≥2 trusted
sources publish the same headline within a short window.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text

from database import Base
from models._schema import TABLE_KW, fk_target


class BreakingAlert(Base):
    __tablename__ = "breaking_alerts"
    __table_args__ = TABLE_KW

    id = Column(Integer, primary_key=True, index=True)
    headline = Column(String(400), nullable=False)
    article_id = Column(Integer, ForeignKey(fk_target("articles")), nullable=True)
    state = Column(String(40), index=True, nullable=False, default="india")
    language = Column(String(8), index=True, nullable=False, default="en")
    sources_count = Column(Integer, nullable=False, default=1)        # how many outlets agree
    note = Column(Text, nullable=True)

    expires_at = Column(DateTime, nullable=False, index=True)        # surface until this time
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
