"""
services/email_db.py
--------------------
SQLite token store for Gmail OAuth.

Why SQLite (not Postgres): Vaani's backend is a single Render free-tier
container; tokens are tiny and scoped per `user_token` (the device
UUID generated by the frontend on first run). When we graduate to
multi-tenant or shared infra, swap this to the same Postgres the other
Chitti products use — same row shape works.

One row per (user_token, provider) — `provider` is forward-looking
(Gmail today, Outlook/Microsoft Graph tomorrow).
"""
from __future__ import annotations

import json
import os
import sqlite3
import threading
import time
from typing import Optional

_LOCK = threading.Lock()
_DB_PATH = os.environ.get("VAANI_TOKEN_DB", "/tmp/chitti_vaani_tokens.sqlite")


def _conn():
    c = sqlite3.connect(_DB_PATH, timeout=10.0, isolation_level=None)
    c.execute("PRAGMA journal_mode=WAL")
    c.execute("PRAGMA synchronous=NORMAL")
    return c


def init_db() -> None:
    with _LOCK, _conn() as c:
        c.execute(
            """
            CREATE TABLE IF NOT EXISTS oauth_tokens (
                user_token   TEXT NOT NULL,
                provider     TEXT NOT NULL,
                email        TEXT,
                access_token TEXT NOT NULL,
                refresh_token TEXT,
                token_uri    TEXT,
                client_id    TEXT,
                client_secret TEXT,
                scopes       TEXT,
                expiry       INTEGER,
                created_at   INTEGER NOT NULL,
                updated_at   INTEGER NOT NULL,
                PRIMARY KEY (user_token, provider)
            )
            """
        )
        c.execute(
            """
            CREATE TABLE IF NOT EXISTS oauth_state (
                state        TEXT PRIMARY KEY,
                user_token   TEXT NOT NULL,
                provider     TEXT NOT NULL,
                created_at   INTEGER NOT NULL
            )
            """
        )


def save_state(state: str, user_token: str, provider: str = "gmail") -> None:
    with _LOCK, _conn() as c:
        c.execute(
            "INSERT OR REPLACE INTO oauth_state(state, user_token, provider, created_at) VALUES (?,?,?,?)",
            (state, user_token, provider, int(time.time())),
        )
        # Sweep states older than 10 minutes
        c.execute("DELETE FROM oauth_state WHERE created_at < ?", (int(time.time()) - 600,))


def pop_state(state: str) -> Optional[dict]:
    with _LOCK, _conn() as c:
        row = c.execute(
            "SELECT user_token, provider FROM oauth_state WHERE state=?", (state,)
        ).fetchone()
        if not row:
            return None
        c.execute("DELETE FROM oauth_state WHERE state=?", (state,))
        return {"user_token": row[0], "provider": row[1]}


def save_token(user_token: str, provider: str, payload: dict) -> None:
    now = int(time.time())
    with _LOCK, _conn() as c:
        c.execute(
            """
            INSERT OR REPLACE INTO oauth_tokens
              (user_token, provider, email, access_token, refresh_token, token_uri,
               client_id, client_secret, scopes, expiry, created_at, updated_at)
            VALUES (?,?,?,?,?,?,?,?,?,?,
                    COALESCE((SELECT created_at FROM oauth_tokens WHERE user_token=? AND provider=?), ?),
                    ?)
            """,
            (
                user_token, provider,
                payload.get("email"),
                payload.get("access_token") or "",
                payload.get("refresh_token"),
                payload.get("token_uri"),
                payload.get("client_id"),
                payload.get("client_secret"),
                json.dumps(payload.get("scopes") or []),
                int(payload.get("expiry") or 0),
                user_token, provider, now,
                now,
            ),
        )


def load_token(user_token: str, provider: str = "gmail") -> Optional[dict]:
    with _LOCK, _conn() as c:
        row = c.execute(
            """SELECT email, access_token, refresh_token, token_uri, client_id,
                      client_secret, scopes, expiry
                 FROM oauth_tokens WHERE user_token=? AND provider=?""",
            (user_token, provider),
        ).fetchone()
    if not row:
        return None
    return {
        "email": row[0],
        "access_token": row[1],
        "refresh_token": row[2],
        "token_uri": row[3],
        "client_id": row[4],
        "client_secret": row[5],
        "scopes": json.loads(row[6] or "[]"),
        "expiry": row[7],
    }


def delete_token(user_token: str, provider: str = "gmail") -> bool:
    with _LOCK, _conn() as c:
        cur = c.execute(
            "DELETE FROM oauth_tokens WHERE user_token=? AND provider=?",
            (user_token, provider),
        )
        return (cur.rowcount or 0) > 0


# Initialise on import (idempotent)
init_db()
