"""
tools/email_quality_status.py
-----------------------------
Mail QUALITY_STATUS.md to FOUNDER_EMAIL via the chitti-founder SMTP helper.

Reuses `lib.founder_report.send_report_email` so the email path is the same
one used by the daily / weekly Chitti Founder reports — no parallel transport,
no risk of drift.

Behavior:
  - SMTP env vars set (FOUNDER_SMTP_HOST / USER / PASS): emails the file.
  - SMTP env vars NOT set: logs the intent and exits 0 — first-deploy honesty
    (matches the `Honest stubs over fake demos` rule in SAHAYAI_MASTER.md §3).

Usage:
    python tools/email_quality_status.py
"""
from __future__ import annotations

import logging
import os
import sys
from pathlib import Path


logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("email-quality-status")


def _render_html(md_text: str) -> str:
    """Wrap the markdown body in a minimal HTML shell. We rely on the
    recipient's mail client to render markdown well enough — no markdown
    parser dependency."""
    body = (md_text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))
    return (
        "<html><body style=\"font-family: -apple-system, Segoe UI, sans-serif; "
        "max-width: 980px; margin: 24px auto; padding: 0 16px;\">"
        "<h2 style=\"color:#1a1a1a;\">Chitti — Enterprise Quality Audit</h2>"
        "<p style=\"color:#555;\">Generated by Claude Opus 4.7 (1M context). "
        "Trigger: Sire's \"ENTERPRISE QUALITY AUDIT — Priority 1\" message. "
        "Full markdown follows verbatim.</p>"
        "<hr/>"
        f"<pre style=\"white-space: pre-wrap; font-family: ui-monospace, monospace; "
        f"font-size: 13px; line-height: 1.5;\">{body}</pre>"
        "</body></html>"
    )


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    md_path = repo_root / "QUALITY_STATUS.md"
    if not md_path.exists():
        log.error("QUALITY_STATUS.md not found at %s", md_path)
        return 2
    md = md_path.read_text(encoding="utf-8")

    # Wire chitti-founder/backend on sys.path so we can import its lib.
    sys.path.insert(0, str(repo_root / "chitti-founder" / "backend"))
    try:
        from lib.founder_report import FOUNDER_EMAIL, send_report_email  # type: ignore
    except Exception as e:  # noqa: BLE001
        log.error("could not import chitti-founder send helper: %s", e)
        return 3

    if not (os.environ.get("FOUNDER_SMTP_HOST")
            and os.environ.get("FOUNDER_SMTP_USER")
            and os.environ.get("FOUNDER_SMTP_PASS")):
        log.info(
            "SMTP env vars not set on this host — emailing skipped. "
            "QUALITY_STATUS.md is the canonical artifact at the repo root. "
            "The next chitti-founder deploy will have the env vars and can be "
            "re-triggered via `POST /admin/founder/send-quality-status`."
        )
        return 0

    subject = "[Chitti] Enterprise Quality Audit — 2026-05-14"
    html = _render_html(md)
    ok = send_report_email(subject, html, recipient=FOUNDER_EMAIL)
    log.info("send_report_email ok=%s recipient=%s", ok, FOUNDER_EMAIL)
    return 0 if ok else 4


if __name__ == "__main__":
    raise SystemExit(main())
