// tools/expand_government_schemes.mjs
// Merge research-derived schemes into chitti-government seed (dedup by slug).
// Run: node tools/expand_government_schemes.mjs
// Doctrine: never guess thresholds — leave numeric eligibility fields null when
// unsure (engine returns unknown/skip, never a fabricated "eligible").
import fs from 'node:fs';
import path from 'node:path';

const SEED = path.resolve('chitti-government/backend/data/schemes_seed.json');
const existing = JSON.parse(fs.readFileSync(SEED, 'utf8'));
const have = new Set(existing.map(s => s.slug));

// helper to keep objects terse; null = not constrained
const S = (o) => ({
  level: 'central', benefit_type: 'service', status: 'active', last_verified: '2026-06',
  category: [], occupation: [], caste: [], exclusions: [], documents_required: [],
  rural_urban: 'both', ...o,
});

const NEW = [
  // ── Farmer / Agriculture (PM-KISAN already seeded) ──
  S({ slug:'pmfby', short_code:'PMFBY', name_en:'Pradhan Mantri Fasal Bima Yojana', name_hi:'प्रधानमंत्री फसल बीमा योजना', ministry:'Ministry of Agriculture & Farmers Welfare', category:['agriculture','insurance'], benefit_type:'insurance', benefit_summary_en:'Crop insurance at 2% (Kharif) / 1.5% (Rabi) premium against crop loss.', benefit_summary_hi:'फसल बीमा — खरीफ 2%, रबी 1.5% प्रीमियम पर फसल नुकसान से सुरक्षा।', occupation:['farmer'], documents_required:['Aadhaar','Bank passbook','Land records / sowing certificate'], application_url:'https://pmfby.gov.in/', source_url:'https://pmfby.gov.in/', helpline:'14447' }),
  S({ slug:'kcc', short_code:'KCC', name_en:'Kisan Credit Card', name_hi:'किसान क्रेडिट कार्ड', ministry:'Department of Financial Services', category:['agriculture','credit'], benefit_type:'credit', benefit_summary_en:'Short-term crop loan up to ₹3 lakh at ~4% effective interest (with subvention).', benefit_summary_hi:'₹3 लाख तक की फसल ऋण सुविधा, लगभग 4% ब्याज पर।', occupation:['farmer','fisher','animal-husbandry'], documents_required:['Aadhaar','Land records','Photo','Bank account'], application_url:'https://pmkisan.gov.in/', source_url:'https://www.myscheme.gov.in/schemes/kcc' }),
  S({ slug:'soil-health-card', short_code:'SHC', name_en:'Soil Health Card', name_hi:'मृदा स्वास्थ्य कार्ड', ministry:'Ministry of Agriculture & Farmers Welfare', category:['agriculture'], benefit_summary_en:'Free soil nutrient report + crop-wise fertilizer advice.', benefit_summary_hi:'मुफ्त मिट्टी जांच रिपोर्ट और फसल अनुसार खाद सलाह।', occupation:['farmer'], documents_required:['Land details'], application_url:'https://soilhealth.dac.gov.in/', source_url:'https://soilhealth.dac.gov.in/' }),
  S({ slug:'pm-kusum', short_code:'PM-KUSUM', name_en:'PM-KUSUM (Solar Pump Subsidy)', name_hi:'पीएम-कुसुम (सौर पंप सब्सिडी)', ministry:'Ministry of New & Renewable Energy', category:['agriculture','energy','subsidy'], benefit_type:'subsidy', benefit_summary_en:'Subsidy for solar pumps and grid-connected solar for farmers.', benefit_summary_hi:'किसानों के लिए सौर पंप व सौर ऊर्जा पर सब्सिडी।', occupation:['farmer'], documents_required:['Aadhaar','Land records','Bank account'], application_url:'https://pmkusum.mnre.gov.in/', source_url:'https://pmkusum.mnre.gov.in/' }),
  S({ slug:'enam', short_code:'eNAM', name_en:'National Agriculture Market (eNAM)', name_hi:'राष्ट्रीय कृषि बाज़ार (ई-नाम)', ministry:'Ministry of Agriculture & Farmers Welfare', category:['agriculture'], benefit_summary_en:'Online mandi trading platform for better crop price discovery.', benefit_summary_hi:'बेहतर फसल मूल्य के लिए ऑनलाइन मंडी मंच।', occupation:['farmer','trader'], documents_required:['Aadhaar','Bank account','Mandi registration'], application_url:'https://enam.gov.in/', source_url:'https://enam.gov.in/' }),
  S({ slug:'pm-kisan-maandhan', short_code:'PM-KMY', name_en:'PM Kisan Maandhan Yojana', name_hi:'पीएम किसान मानधन योजना', ministry:'Ministry of Agriculture & Farmers Welfare', category:['agriculture','pension'], benefit_type:'pension', benefit_summary_en:'₹3,000/month pension at 60 for small/marginal farmers (contributory).', benefit_summary_hi:'छोटे किसानों को 60 साल पर ₹3,000 मासिक पेंशन (अंशदायी)।', age_min:18, age_max:40, occupation:['farmer'], documents_required:['Aadhaar','Savings/Jan Dhan account'], application_url:'https://maandhan.in/', source_url:'https://maandhan.in/' }),
  S({ slug:'agri-infra-fund', short_code:'AIF', name_en:'Agriculture Infrastructure Fund', name_hi:'कृषि अवसंरचना कोष', ministry:'Ministry of Agriculture & Farmers Welfare', category:['agriculture','credit'], benefit_type:'credit', benefit_summary_en:'Financing with 3% interest subvention for post-harvest infrastructure.', benefit_summary_hi:'फसल-उपरांत ढांचे के लिए 3% ब्याज छूट के साथ वित्त।', occupation:['farmer','entrepreneur'], documents_required:['Project report','KYC','Land/lease docs'], application_url:'https://agriinfra.dac.gov.in/', source_url:'https://agriinfra.dac.gov.in/' }),

  // ── Women / girl-child (Sukanya, PMMVY, Ujjwala may already be seeded — dedup handles) ──
  S({ slug:'pmmvy', short_code:'PMMVY', name_en:'PM Matru Vandana Yojana 2.0', name_hi:'प्रधानमंत्री मातृ वंदना योजना 2.0', ministry:'Ministry of Women & Child Development', category:['women','maternity','cash'], benefit_type:'cash', benefit_summary_en:'₹5,000 for first child (₹6,000 for second if a girl) to pregnant & lactating mothers.', benefit_summary_hi:'गर्भवती/धात्री माताओं को पहले बच्चे पर ₹5,000 (दूसरी बेटी पर ₹6,000)।', gender:'f', age_min:19, occupation:[], documents_required:['Aadhaar','Bank account','MCP card'], application_url:'https://pmmvy.wcd.gov.in/', source_url:'https://pmmvy.wcd.gov.in/' }),
  S({ slug:'sukanya-samriddhi', short_code:'SSY', name_en:'Sukanya Samriddhi Yojana', name_hi:'सुकन्या समृद्धि योजना', ministry:'Ministry of Finance', category:['women','savings'], benefit_type:'savings', benefit_summary_en:'High-interest small-savings account for a girl child under 10, with 80C tax benefit.', benefit_summary_hi:'10 साल से कम बेटी के लिए ऊँचे ब्याज वाला बचत खाता, 80C कर लाभ।', gender:'f', documents_required:["Girl's birth certificate",'Guardian KYC'], application_url:'https://www.nsiindia.gov.in/', source_url:'https://www.nsiindia.gov.in/' }),
  S({ slug:'ujjwala-2', short_code:'PMUY', name_en:'Pradhan Mantri Ujjwala Yojana 2.0', name_hi:'प्रधानमंत्री उज्ज्वला योजना 2.0', ministry:'Ministry of Petroleum & Natural Gas', category:['women','energy'], benefit_summary_en:'Free LPG connection + first refill + stove for women of poor households.', benefit_summary_hi:'गरीब परिवार की महिलाओं को मुफ्त एलपीजी कनेक्शन, पहला रिफिल व चूल्हा।', gender:'f', bpl_required:true, documents_required:['Aadhaar','Ration card','Bank account'], application_url:'https://www.pmuy.gov.in/', source_url:'https://www.pmuy.gov.in/' }),
  S({ slug:'lakhpati-didi', short_code:'Lakhpati Didi', name_en:'Lakhpati Didi', name_hi:'लखपति दीदी', ministry:'Ministry of Rural Development (DAY-NRLM)', category:['women','livelihood','credit'], benefit_summary_en:'Skilling + subsidised credit so SHG women earn ≥₹1 lakh/year.', benefit_summary_hi:'स्वयं सहायता समूह की महिलाओं को कौशल व सस्ता ऋण ताकि सालाना ₹1 लाख कमाएं।', gender:'f', occupation:['shg-member'], documents_required:['SHG membership','Aadhaar','Bank account'], application_url:'https://lakhpatididi.gov.in/', source_url:'https://lakhpatididi.gov.in/' }),
  S({ slug:'mahila-samman-savings', short_code:'MSSC', name_en:'Mahila Samman Savings Certificate', name_hi:'महिला सम्मान बचत प्रमाणपत्र', ministry:'Ministry of Finance', category:['women','savings'], benefit_type:'savings', status:'closed', benefit_summary_en:'7.5% two-year deposit for women (CLOSED to new deposits after 31 Mar 2025; existing accounts continue).', benefit_summary_hi:'महिलाओं के लिए 7.5% दो-वर्षीय जमा (31 मार्च 2025 के बाद नई जमा बंद)।', gender:'f', documents_required:['KYC','Aadhaar/PAN'], application_url:'https://www.nsiindia.gov.in/', source_url:'https://www.myscheme.gov.in/schemes/mssc' }),
  S({ slug:'ladki-bahin-mh', short_code:'Ladki Bahin', name_en:'Mukhyamantri Majhi Ladki Bahin (Maharashtra)', name_hi:'मुख्यमंत्री माझी लाडकी बहीण', ministry:'Government of Maharashtra', level:'state', state_code:'MH', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'Monthly DBT to eligible women (amount per latest state notification — verify).', benefit_summary_hi:'पात्र महिलाओं को मासिक नकद सहायता (राशि राज्य अधिसूचना अनुसार — पुष्टि करें)।', gender:'f', age_min:21, age_max:65, income_max_annual_inr:250000, documents_required:['Aadhaar','Ration/Voter ID','Bank account','Income/Domicile proof'], application_url:'https://ladakibahin.maharashtra.gov.in/', source_url:'https://www.myscheme.gov.in/schemes/mmlby' }),
  S({ slug:'subhadra-od', short_code:'Subhadra', name_en:'Subhadra Yojana (Odisha)', name_hi:'सुभद्रा योजना (ओडिशा)', ministry:'Government of Odisha', level:'state', state_code:'OD', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'₹50,000 over 5 years (₹10,000/year in two instalments) to eligible women.', benefit_summary_hi:'पात्र महिलाओं को 5 वर्षों में ₹50,000 (हर साल ₹10,000, दो किस्तों में)।', gender:'f', age_min:21, age_max:60, income_max_annual_inr:250000, documents_required:['Aadhaar','Bank account','Residence proof'], application_url:'https://subhadra.odisha.gov.in/', source_url:'https://subhadra.odisha.gov.in/' }),
  S({ slug:'ladli-behna-mp', short_code:'Ladli Behna', name_en:'Mukhyamantri Ladli Behna (Madhya Pradesh)', name_hi:'मुख्यमंत्री लाडली बहना योजना', ministry:'Government of Madhya Pradesh', level:'state', state_code:'MP', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'Monthly cash support to eligible women (amount per latest state notification).', benefit_summary_hi:'पात्र महिलाओं को मासिक नकद सहायता (राशि राज्य अधिसूचना अनुसार)।', gender:'f', documents_required:['Aadhaar','Samagra ID','Bank account'], application_url:'https://cmladlibahna.mp.gov.in/', source_url:'https://cmladlibahna.mp.gov.in/' }),

  // ── Senior citizen ──
  S({ slug:'ignoaps', short_code:'IGNOAPS', name_en:'Indira Gandhi National Old Age Pension (NSAP)', name_hi:'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन', ministry:'Ministry of Rural Development', category:['senior','pension'], benefit_type:'pension', benefit_summary_en:'₹200–₹500/month central pension (plus state top-up) for BPL elderly.', benefit_summary_hi:'बीपीएल वृद्धों को ₹200–₹500 मासिक केंद्रीय पेंशन (राज्य टॉप-अप के साथ)।', age_min:60, bpl_required:true, documents_required:['Aadhaar','BPL/Income proof','Age proof','Bank account'], application_url:'https://nsap.nic.in/', source_url:'https://nsap.nic.in/' }),
  S({ slug:'atal-pension', short_code:'APY', name_en:'Atal Pension Yojana', name_hi:'अटल पेंशन योजना', ministry:'Ministry of Finance (PFRDA)', category:['pension','financial-inclusion'], benefit_type:'pension', benefit_summary_en:'Guaranteed ₹1,000–₹5,000/month pension from age 60 (contributory).', benefit_summary_hi:'60 वर्ष से ₹1,000–₹5,000 मासिक गारंटीड पेंशन (अंशदायी)।', age_min:18, age_max:40, documents_required:['Aadhaar','Bank account','Mobile'], application_url:'https://www.npscra.nsdl.co.in/', source_url:'https://www.npscra.nsdl.co.in/', exclusions:['income-tax payer (since Oct 2022)'] }),
  S({ slug:'scss', short_code:'SCSS', name_en:'Senior Citizen Savings Scheme', name_hi:'वरिष्ठ नागरिक बचत योजना', ministry:'Ministry of Finance', category:['senior','savings'], benefit_type:'savings', benefit_summary_en:'~8.2% deposit up to ₹30 lakh for 5 years for senior citizens.', benefit_summary_hi:'वरिष्ठ नागरिकों के लिए ₹30 लाख तक 5-वर्षीय जमा, लगभग 8.2% ब्याज।', age_min:60, documents_required:['KYC','Age proof'], application_url:'https://www.nsiindia.gov.in/', source_url:'https://www.nsiindia.gov.in/' }),
  S({ slug:'rashtriya-vayoshri', short_code:'RVY', name_en:'Rashtriya Vayoshri Yojana', name_hi:'राष्ट्रीय वयोश्री योजना', ministry:'Ministry of Social Justice & Empowerment', category:['senior'], benefit_summary_en:'Free assisted-living aids and devices for BPL elderly.', benefit_summary_hi:'बीपीएल वृद्धों को मुफ्त सहायक उपकरण।', age_min:60, bpl_required:true, documents_required:['Aadhaar','BPL/Income proof','Age proof'], application_url:'https://alimco.in/', source_url:'https://depwd.gov.in/' }),
  S({ slug:'ayushman-vay-vandana', short_code:'AB Vay Vandana', name_en:'Ayushman Vay Vandana Card (PM-JAY 70+)', name_hi:'आयुष्मान वय वंदना कार्ड (70+)', ministry:'Ministry of Health (NHA)', category:['senior','health','insurance'], benefit_type:'insurance', benefit_amount_inr:500000, benefit_summary_en:'₹5 lakh/year free health cover for ALL citizens aged 70+, regardless of income.', benefit_summary_hi:'70+ सभी नागरिकों को आय की परवाह किए बिना ₹5 लाख वार्षिक मुफ्त स्वास्थ्य कवर।', age_min:70, documents_required:['Aadhaar'], application_url:'https://beneficiary.nha.gov.in/', source_url:'https://beneficiary.nha.gov.in/' }),

  // ── Students / education ──
  S({ slug:'nsp', short_code:'NSP', name_en:'National Scholarship Portal', name_hi:'राष्ट्रीय छात्रवृत्ति पोर्टल', ministry:'MeitY (multiple ministries)', category:['education','scholarship'], benefit_summary_en:'Single window for 100+ central & state scholarships.', benefit_summary_hi:'100+ केंद्रीय व राज्य छात्रवृत्तियों के लिए एकल खिड़की।', occupation:['student'], documents_required:['Aadhaar','Bank account','Income/Caste cert','Marksheet','Bonafide'], application_url:'https://scholarships.gov.in/', source_url:'https://scholarships.gov.in/' }),
  S({ slug:'pm-vidyalaxmi', short_code:'PM-Vidyalaxmi', name_en:'PM Vidyalaxmi (Education Loan)', name_hi:'पीएम विद्यालक्ष्मी (शिक्षा ऋण)', ministry:'Ministry of Education', category:['education','credit'], benefit_type:'credit', benefit_summary_en:'Collateral-free, guarantor-free education loan with interest subvention for top institutions.', benefit_summary_hi:'शीर्ष संस्थानों के लिए बिना गारंटी शिक्षा ऋण, ब्याज छूट के साथ।', occupation:['student'], income_max_annual_inr:800000, documents_required:['Aadhaar','Admission proof','Income proof'], application_url:'https://www.pmvidyalaxmi.co.in/', source_url:'https://www.pmvidyalaxmi.co.in/' }),
  S({ slug:'aicte-pragati', short_code:'Pragati', name_en:'AICTE Pragati Scholarship (Girls)', name_hi:'एआईसीटीई प्रगति छात्रवृत्ति (छात्राएं)', ministry:'Ministry of Education (AICTE)', category:['education','scholarship','women'], benefit_summary_en:'₹50,000/year for girl students in AICTE-approved technical courses.', benefit_summary_hi:'एआईसीटीई तकनीकी पाठ्यक्रमों की छात्राओं को ₹50,000 वार्षिक।', gender:'f', occupation:['student'], income_max_annual_inr:800000, documents_required:['UDID/Income cert','Admission','Marksheet'], application_url:'https://scholarships.gov.in/', source_url:'https://www.aicte-india.org/' }),
  S({ slug:'aicte-saksham', short_code:'Saksham', name_en:'AICTE Saksham Scholarship (PwD)', name_hi:'एआईसीटीई सक्षम छात्रवृत्ति (दिव्यांग)', ministry:'Ministry of Education (AICTE)', category:['education','scholarship','disability'], benefit_summary_en:'₹50,000/year for differently-abled students (≥40%) in technical courses.', benefit_summary_hi:'तकनीकी पाठ्यक्रमों में दिव्यांग (≥40%) छात्रों को ₹50,000 वार्षिक।', disability_required:true, occupation:['student'], income_max_annual_inr:800000, documents_required:['UDID/Disability cert','Income','Admission'], application_url:'https://scholarships.gov.in/', source_url:'https://www.aicte-india.org/' }),
  S({ slug:'nmms', short_code:'NMMS', name_en:'National Means-cum-Merit Scholarship', name_hi:'राष्ट्रीय साधन-सह-मेधा छात्रवृत्ति', ministry:'Ministry of Education', category:['education','scholarship'], benefit_summary_en:'₹12,000/year for Class 9–12 means+merit students.', benefit_summary_hi:'कक्षा 9–12 के मेधावी जरूरतमंद छात्रों को ₹12,000 वार्षिक।', occupation:['student'], income_max_annual_inr:350000, documents_required:['Income','Marksheet','Bank'], application_url:'https://scholarships.gov.in/', source_url:'https://scholarships.gov.in/' }),
  S({ slug:'pm-yasasvi', short_code:'PM-YASASVI', name_en:'PM YASASVI Scholarship (OBC/EBC/DNT)', name_hi:'पीएम यशस्वी छात्रवृत्ति', ministry:'Ministry of Social Justice & Empowerment', category:['education','scholarship'], benefit_summary_en:'₹75,000 (Class 9) / ₹1.25 lakh (Class 11) for OBC/EBC/DNT students.', benefit_summary_hi:'ओबीसी/ईबीसी/डीएनटी छात्रों को ₹75,000 (कक्षा 9) / ₹1.25 लाख (कक्षा 11)।', caste:['OBC'], occupation:['student'], income_max_annual_inr:250000, documents_required:['Caste','Income','Marksheet'], application_url:'https://scholarships.gov.in/', source_url:'https://www.myscheme.gov.in/schemes/pm-yasasvitcceobcebcdnts' }),
  S({ slug:'pm-internship', short_code:'PM Internship', name_en:'PM Internship Scheme', name_hi:'पीएम इंटर्नशिप योजना', ministry:'Ministry of Corporate Affairs', category:['education','employment'], status:'verify', benefit_summary_en:'12-month internship in top companies with ₹5,000/month stipend + ₹6,000 one-time.', benefit_summary_hi:'शीर्ष कंपनियों में 12-माह इंटर्नशिप, ₹5,000 मासिक भत्ता व ₹6,000 एकमुश्त।', age_min:21, age_max:24, income_max_annual_inr:800000, documents_required:['Aadhaar','Qualification','Bank account'], application_url:'https://pminternship.mca.gov.in/', source_url:'https://pminternship.mca.gov.in/' }),

  // ── Workers / labour ──
  S({ slug:'e-shram', short_code:'e-Shram', name_en:'e-Shram (Unorganised Worker Registration)', name_hi:'ई-श्रम (असंगठित श्रमिक पंजीकरण)', ministry:'Ministry of Labour & Employment', category:['worker','social-security'], benefit_summary_en:'National worker database + ₹2 lakh accidental insurance for unorganised workers.', benefit_summary_hi:'असंगठित श्रमिकों के लिए राष्ट्रीय डेटाबेस व ₹2 लाख दुर्घटना बीमा।', age_min:16, age_max:59, documents_required:['Aadhaar','Aadhaar-linked mobile','Bank account'], application_url:'https://eshram.gov.in/', source_url:'https://eshram.gov.in/', exclusions:['EPFO/ESIC member','income-tax payer'] }),
  S({ slug:'pm-sym', short_code:'PM-SYM', name_en:'PM Shram Yogi Maandhan', name_hi:'पीएम श्रम योगी मानधन', ministry:'Ministry of Labour & Employment', category:['worker','pension'], benefit_type:'pension', benefit_summary_en:'₹3,000/month pension at 60 for unorganised workers (contributory).', benefit_summary_hi:'असंगठित श्रमिकों को 60 वर्ष पर ₹3,000 मासिक पेंशन (अंशदायी)।', age_min:18, age_max:40, income_max_annual_inr:180000, documents_required:['Aadhaar','Savings/Jan Dhan account','Mobile'], application_url:'https://maandhan.in/', source_url:'https://maandhan.in/' }),
  S({ slug:'pm-vishwakarma', short_code:'PM Vishwakarma', name_en:'PM Vishwakarma', name_hi:'पीएम विश्वकर्मा', ministry:'Ministry of MSME', category:['worker','credit','skill'], benefit_summary_en:'Digital ID, ₹15k toolkit voucher, training + stipend, loans up to ₹3 lakh @5% for 18 artisan trades.', benefit_summary_hi:'18 पारंपरिक शिल्पकार व्यवसायों को डिजिटल आईडी, ₹15,000 टूलकिट, प्रशिक्षण व ₹3 लाख तक 5% ऋण।', age_min:18, occupation:['artisan'], documents_required:['Aadhaar','Mobile','Bank account','Ration card'], application_url:'https://pmvishwakarma.gov.in/', source_url:'https://pmvishwakarma.gov.in/' }),
  S({ slug:'pm-svanidhi', short_code:'PM-SVANidhi', name_en:'PM SVANidhi (Street Vendors)', name_hi:'पीएम स्वनिधि (स्ट्रीट वेंडर)', ministry:'Ministry of Housing & Urban Affairs', category:['worker','credit'], benefit_type:'credit', benefit_summary_en:'Collateral-free working-capital loans (₹10k → ₹20k → ₹50k) for urban street vendors.', benefit_summary_hi:'शहरी स्ट्रीट वेंडरों को बिना गारंटी कार्यशील पूंजी ऋण (₹10k → ₹20k → ₹50k)।', occupation:['street-vendor'], rural_urban:'urban', documents_required:['Aadhaar','Vending certificate','Bank account'], application_url:'https://pmsvanidhi.mohua.gov.in/', source_url:'https://pmsvanidhi.mohua.gov.in/' }),
  S({ slug:'esic', short_code:'ESIC', name_en:'Employees State Insurance (ESI)', name_hi:'कर्मचारी राज्य बीमा (ईएसआई)', ministry:'Ministry of Labour & Employment', category:['worker','health','insurance'], benefit_summary_en:'Medical + cash benefits for organised-sector workers earning ≤₹21,000/month.', benefit_summary_hi:'₹21,000/माह तक कमाने वाले संगठित श्रमिकों को चिकित्सा व नकद लाभ।', income_max_annual_inr:252000, documents_required:['Insurance number','Employer registration'], application_url:'https://www.esic.gov.in/', source_url:'https://www.esic.gov.in/' }),

  // ── Health ──
  S({ slug:'pmjay', short_code:'PM-JAY', name_en:'Ayushman Bharat PM-JAY', name_hi:'आयुष्मान भारत पीएम-जय', ministry:'Ministry of Health (NHA)', category:['health','insurance'], benefit_type:'insurance', benefit_amount_inr:500000, benefit_summary_en:'₹5 lakh/family/year cashless secondary & tertiary hospital care.', benefit_summary_hi:'प्रति परिवार सालाना ₹5 लाख तक मुफ्त अस्पताल इलाज।', secc_deprivation_required:true, documents_required:['Aadhaar','Ration card'], application_url:'https://beneficiary.nha.gov.in/', source_url:'https://pmjay.gov.in/', helpline:'14555' }),
  S({ slug:'abha', short_code:'ABHA', name_en:'Ayushman Bharat Health Account (ABHA)', name_hi:'आयुष्मान भारत हेल्थ अकाउंट', ministry:'Ministry of Health (NHA/ABDM)', category:['health'], benefit_summary_en:'14-digit health ID linking your digital health records (voluntary).', benefit_summary_hi:'आपके डिजिटल स्वास्थ्य रिकॉर्ड जोड़ने वाली 14-अंकीय हेल्थ आईडी।', documents_required:['Aadhaar or mobile'], application_url:'https://abha.abdm.gov.in/', source_url:'https://abha.abdm.gov.in/' }),
  S({ slug:'janani-suraksha', short_code:'JSY', name_en:'Janani Suraksha Yojana', name_hi:'जननी सुरक्षा योजना', ministry:'Ministry of Health', category:['health','women','maternity','cash'], benefit_type:'cash', benefit_summary_en:'Cash assistance for institutional delivery (rural/urban, BPL/SC/ST priority).', benefit_summary_hi:'संस्थागत प्रसव पर नकद सहायता (बीपीएल/एससी/एसटी को प्राथमिकता)।', gender:'f', documents_required:['Aadhaar','MCP card','Bank','JSY card'], application_url:'https://nhm.gov.in/', source_url:'https://nhm.gov.in/' }),
  S({ slug:'jan-aushadhi', short_code:'PMBJP', name_en:'PM Jan Aushadhi (Generic Medicines)', name_hi:'पीएम जन औषधि (जेनेरिक दवाएं)', ministry:'Department of Pharmaceuticals', category:['health'], benefit_summary_en:'Quality generic medicines at 50–90% lower prices, open to all.', benefit_summary_hi:'सभी के लिए 50–90% सस्ती गुणवत्तापूर्ण जेनेरिक दवाएं।', documents_required:[], application_url:'https://janaushadhi.gov.in/', source_url:'https://janaushadhi.gov.in/' }),

  // ── Housing / sanitation ──
  S({ slug:'pmay-g', short_code:'PMAY-G', name_en:'Pradhan Mantri Awas Yojana - Gramin', name_hi:'प्रधानमंत्री आवास योजना - ग्रामीण', ministry:'Ministry of Rural Development', category:['housing'], benefit_type:'subsidy', benefit_summary_en:'₹1.2–1.3 lakh assistance to build a pucca house for rural houseless/kutcha families.', benefit_summary_hi:'ग्रामीण बेघर/कच्चे घर वालों को पक्का घर बनाने हेतु ₹1.2–1.3 लाख सहायता।', rural_urban:'rural', secc_deprivation_required:true, documents_required:['Aadhaar','Job card','Bank account','SECC'], application_url:'https://pmayg.nic.in/', source_url:'https://pmayg.nic.in/' }),
  S({ slug:'pmay-u-2', short_code:'PMAY-U 2.0', name_en:'Pradhan Mantri Awas Yojana - Urban 2.0', name_hi:'प्रधानमंत्री आवास योजना - शहरी 2.0', ministry:'Ministry of Housing & Urban Affairs', category:['housing'], benefit_type:'subsidy', benefit_summary_en:'Up to ₹2.5 lakh assistance for urban EWS/LIG/MIG housing.', benefit_summary_hi:'शहरी ईडब्ल्यूएस/एलआईजी/एमआईजी आवास हेतु ₹2.5 लाख तक सहायता।', rural_urban:'urban', documents_required:['Aadhaar','Income proof','Bank account'], application_url:'https://pmay-urban.gov.in/', source_url:'https://pmay-urban.gov.in/' }),
  S({ slug:'swachh-bharat', short_code:'SBM', name_en:'Swachh Bharat Mission (Toilet)', name_hi:'स्वच्छ भारत मिशन (शौचालय)', ministry:'Jal Shakti / MoHUA', category:['sanitation'], benefit_type:'subsidy', benefit_summary_en:'~₹12,000 incentive to build a household toilet.', benefit_summary_hi:'घरेलू शौचालय बनाने हेतु लगभग ₹12,000 प्रोत्साहन।', documents_required:['Aadhaar','Bank account'], application_url:'https://swachhbharatmission.gov.in/', source_url:'https://swachhbharatmission.gov.in/' }),
  S({ slug:'jal-jeevan', short_code:'JJM', name_en:'Jal Jeevan Mission (Har Ghar Jal)', name_hi:'जल जीवन मिशन (हर घर जल)', ministry:'Ministry of Jal Shakti', category:['utility'], benefit_summary_en:'Functional tap water connection to every rural household.', benefit_summary_hi:'हर ग्रामीण घर को नल से जल कनेक्शन।', rural_urban:'rural', documents_required:[], application_url:'https://jaljeevanmission.gov.in/', source_url:'https://jaljeevanmission.gov.in/' }),

  // ── Disabled ──
  S({ slug:'udid', short_code:'UDID', name_en:'Unique Disability ID (UDID)', name_hi:'विशिष्ट दिव्यांगता पहचान-पत्र', ministry:'Dept of Empowerment of PwD (DEPwD)', category:['disability'], benefit_summary_en:'Single disability certificate + ID card — the gateway to all PwD benefits.', benefit_summary_hi:'एकल दिव्यांगता प्रमाणपत्र व पहचान-पत्र — सभी दिव्यांग लाभों का प्रवेश-द्वार।', disability_required:true, documents_required:['Aadhaar','Medical assessment','Photo'], application_url:'https://www.swavlambancard.gov.in/', source_url:'https://www.swavlambancard.gov.in/' }),
  S({ slug:'adip', short_code:'ADIP', name_en:'ADIP (Assistive Aids & Appliances)', name_hi:'एडीआईपी (सहायक उपकरण)', ministry:'Dept of Empowerment of PwD (DEPwD)', category:['disability'], benefit_summary_en:'Free/subsidised assistive aids and appliances for persons with disability.', benefit_summary_hi:'दिव्यांगजनों को मुफ्त/रियायती सहायक उपकरण।', disability_required:true, documents_required:['UDID/Disability cert','Income','Aadhaar'], application_url:'https://depwd.gov.in/', source_url:'https://depwd.gov.in/' }),
  S({ slug:'igndps', short_code:'IGNDPS', name_en:'Indira Gandhi National Disability Pension', name_hi:'इंदिरा गांधी राष्ट्रीय दिव्यांगता पेंशन', ministry:'Ministry of Rural Development (NSAP)', category:['disability','pension'], benefit_type:'pension', benefit_summary_en:'₹300–₹500/month pension for BPL persons with severe disability.', benefit_summary_hi:'गंभीर दिव्यांगता वाले बीपीएल व्यक्तियों को ₹300–₹500 मासिक पेंशन।', age_min:18, age_max:79, bpl_required:true, disability_required:true, documents_required:['UDID','BPL/Income','Bank'], application_url:'https://nsap.nic.in/', source_url:'https://nsap.nic.in/' }),

  // ── Business / MSME / startup ──
  S({ slug:'udyam', short_code:'Udyam', name_en:'Udyam Registration (MSME)', name_hi:'उद्यम पंजीकरण (एमएसएमई)', ministry:'Ministry of MSME', category:['business'], benefit_summary_en:'Free MSME registration — gateway to MSME benefits and priority lending.', benefit_summary_hi:'मुफ्त एमएसएमई पंजीकरण — एमएसएमई लाभ व प्राथमिकता ऋण का प्रवेश-द्वार।', occupation:['business-owner'], documents_required:['Aadhaar','PAN','GSTIN'], application_url:'https://udyamregistration.gov.in/', source_url:'https://udyamregistration.gov.in/' }),
  S({ slug:'pm-mudra', short_code:'MUDRA', name_en:'PM MUDRA Yojana', name_hi:'पीएम मुद्रा योजना', ministry:'Ministry of Finance (MUDRA)', category:['business','credit'], benefit_type:'credit', benefit_summary_en:'Loans up to ₹20 lakh (Shishu/Kishore/Tarun) for non-farm micro enterprises.', benefit_summary_hi:'गैर-कृषि सूक्ष्म उद्यमों को ₹20 लाख तक ऋण (शिशु/किशोर/तरुण)।', occupation:['business-owner'], documents_required:['KYC','Business proof','Bank account'], application_url:'https://www.mudra.org.in/', source_url:'https://www.mudra.org.in/' }),
  S({ slug:'stand-up-india', short_code:'Stand-Up India', name_en:'Stand-Up India', name_hi:'स्टैंड-अप इंडिया', ministry:'Department of Financial Services', category:['business','credit','women'], benefit_type:'credit', benefit_summary_en:'Bank loans ₹10 lakh–₹1 crore for SC/ST and women entrepreneurs (greenfield).', benefit_summary_hi:'एससी/एसटी व महिला उद्यमियों को ₹10 लाख–₹1 करोड़ ऋण (नई इकाई)।', age_min:18, documents_required:['KYC','Project report','Caste/Gender proof'], application_url:'https://www.standupmitra.in/', source_url:'https://www.standupmitra.in/' }),
  S({ slug:'startup-india', short_code:'Startup India', name_en:'Startup India (DPIIT Recognition)', name_hi:'स्टार्टअप इंडिया (डीपीआईआईटी)', ministry:'DPIIT', category:['business','startup'], benefit_summary_en:'Tax holiday, easier compliance, funding access, IPR fast-track for recognised startups.', benefit_summary_hi:'मान्यता-प्राप्त स्टार्टअप को कर छूट, आसान अनुपालन, वित्त व आईपीआर सुविधा।', occupation:['business-owner'], documents_required:['Incorporation certificate','PAN','Pitch'], application_url:'https://www.startupindia.gov.in/', source_url:'https://www.startupindia.gov.in/' }),
  S({ slug:'pmegp', short_code:'PMEGP', name_en:'PM Employment Generation Programme', name_hi:'पीएम रोजगार सृजन कार्यक्रम', ministry:'Ministry of MSME (KVIC)', category:['business','credit','employment'], benefit_type:'subsidy', benefit_summary_en:'15–35% margin-money subsidy for new micro enterprises.', benefit_summary_hi:'नई सूक्ष्म इकाइयों को 15–35% मार्जिन-मनी सब्सिडी।', age_min:18, documents_required:['Aadhaar','Project report','Caste/Special-category proof'], application_url:'https://www.kviconline.gov.in/pmegpeportal/', source_url:'https://www.kviconline.gov.in/pmegpeportal/' }),

  // ── Financial inclusion ──
  S({ slug:'pmjdy', short_code:'PMJDY', name_en:'PM Jan Dhan Yojana', name_hi:'पीएम जन धन योजना', ministry:'Department of Financial Services', category:['financial-inclusion'], benefit_summary_en:'Zero-balance bank account + RuPay card + ₹2 lakh accident cover + overdraft.', benefit_summary_hi:'शून्य-बैलेंस बैंक खाता + रुपे कार्ड + ₹2 लाख दुर्घटना कवर + ओवरड्राफ्ट।', documents_required:['Aadhaar or any valid ID'], application_url:'https://pmjdy.gov.in/', source_url:'https://pmjdy.gov.in/' }),
  S({ slug:'pmjjby', short_code:'PMJJBY', name_en:'PM Jeevan Jyoti Bima Yojana', name_hi:'पीएम जीवन ज्योति बीमा योजना', ministry:'Ministry of Finance', category:['financial-inclusion','insurance'], benefit_type:'insurance', benefit_amount_inr:200000, benefit_summary_en:'₹2 lakh life cover for ₹436/year.', benefit_summary_hi:'₹436 सालाना में ₹2 लाख जीवन बीमा।', age_min:18, age_max:50, documents_required:['Aadhaar','Bank account'], application_url:'https://www.jansuraksha.gov.in/', source_url:'https://www.jansuraksha.gov.in/' }),
  S({ slug:'pmsby', short_code:'PMSBY', name_en:'PM Suraksha Bima Yojana', name_hi:'पीएम सुरक्षा बीमा योजना', ministry:'Ministry of Finance', category:['financial-inclusion','insurance'], benefit_type:'insurance', benefit_amount_inr:200000, benefit_summary_en:'₹2 lakh accident cover for ₹20/year.', benefit_summary_hi:'₹20 सालाना में ₹2 लाख दुर्घटना बीमा।', age_min:18, age_max:70, documents_required:['Aadhaar','Bank account'], application_url:'https://www.jansuraksha.gov.in/', source_url:'https://www.jansuraksha.gov.in/' }),

  // ── Energy / utility ──
  S({ slug:'pm-surya-ghar', short_code:'PM Surya Ghar', name_en:'PM Surya Ghar: Muft Bijli Yojana', name_hi:'पीएम सूर्य घर: मुफ्त बिजली योजना', ministry:'Ministry of New & Renewable Energy', category:['energy','subsidy','housing'], benefit_type:'subsidy', benefit_summary_en:'Up to ₹78,000 subsidy for rooftop solar; ~300 free units/month.', benefit_summary_hi:'छत पर सौर पैनल हेतु ₹78,000 तक सब्सिडी; ~300 यूनिट मुफ्त बिजली प्रति माह।', documents_required:['Aadhaar','Electricity bill/consumer no.','Bank account'], application_url:'https://pmsuryaghar.gov.in/', source_url:'https://pmsuryaghar.gov.in/' }),

  // ── Caste / social-justice ──
  S({ slug:'post-matric-scst-obc', short_code:'Post-Matric', name_en:'Post-Matric Scholarship (SC/ST/OBC)', name_hi:'पोस्ट-मैट्रिक छात्रवृत्ति (एससी/एसटी/ओबीसी)', ministry:'Ministry of Social Justice / Tribal Affairs', category:['education','scholarship'], benefit_summary_en:'Fee + maintenance support for SC/ST/OBC post-matric students.', benefit_summary_hi:'एससी/एसटी/ओबीसी पोस्ट-मैट्रिक छात्रों को फीस व निर्वाह सहायता।', caste:['SC','ST','OBC'], occupation:['student'], documents_required:['Caste cert','Income','Bank','Marksheet'], application_url:'https://scholarships.gov.in/', source_url:'https://scholarships.gov.in/' }),
  S({ slug:'pm-janman', short_code:'PM-JANMAN', name_en:'PM-JANMAN (PVTG Development)', name_hi:'पीएम-जनमन (पीवीटीजी विकास)', ministry:'Ministry of Tribal Affairs', category:['tribal','housing','utility'], status:'verify', benefit_summary_en:'11 interventions (housing, water, road, health, education) for particularly vulnerable tribal groups.', benefit_summary_hi:'विशेष रूप से कमजोर जनजातीय समूहों हेतु 11 हस्तक्षेप (आवास, जल, सड़क, स्वास्थ्य, शिक्षा)।', caste:['ST'], documents_required:['Aadhaar (where available)','Community ID'], application_url:'https://tribal.nic.in/', source_url:'https://tribal.nic.in/' }),

  // ── Major state flagships (verify) ──
  S({ slug:'gruha-lakshmi-ka', short_code:'Gruha Lakshmi', name_en:'Gruha Lakshmi (Karnataka)', name_hi:'गृह लक्ष्मी (कर्नाटक)', ministry:'Government of Karnataka', level:'state', state_code:'KA', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'Monthly cash to women heads of family (amount per latest state notification).', benefit_summary_hi:'परिवार की महिला मुखिया को मासिक नकद (राशि राज्य अधिसूचना अनुसार)।', gender:'f', documents_required:['Aadhaar','Ration card','Bank account'], application_url:'https://sevasindhugs.karnataka.gov.in/', source_url:'https://sevasindhugs.karnataka.gov.in/' }),
  S({ slug:'magalir-urimai-tn', short_code:'Magalir Urimai', name_en:'Kalaignar Magalir Urimai Thogai (Tamil Nadu)', name_hi:'कलैगनार मगलिर उरिमई थोगई (तमिलनाडु)', ministry:'Government of Tamil Nadu', level:'state', state_code:'TN', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'₹1,000/month to eligible women heads of household.', benefit_summary_hi:'पात्र महिला गृह-मुखिया को ₹1,000 मासिक।', gender:'f', documents_required:['Aadhaar','Ration card','Bank account'], application_url:'https://www.tn.gov.in/', source_url:'https://www.tn.gov.in/' }),
  S({ slug:'lakshmir-bhandar-wb', short_code:'Lakshmir Bhandar', name_en:'Lakshmir Bhandar (West Bengal)', name_hi:'लक्ष्मीर भंडार (पश्चिम बंगाल)', ministry:'Government of West Bengal', level:'state', state_code:'WB', status:'verify', category:['women','cash'], benefit_type:'cash', benefit_summary_en:'₹1,000–₹1,200/month support to women heads of family.', benefit_summary_hi:'परिवार की महिला मुखिया को ₹1,000–₹1,200 मासिक सहायता।', gender:'f', documents_required:['Aadhaar','Swasthya Sathi card','Bank account'], application_url:'https://socialsecurity.wb.gov.in/', source_url:'https://wb.gov.in/' }),
  S({ slug:'kanyashree-wb', short_code:'Kanyashree', name_en:'Kanyashree Prakalpa (West Bengal)', name_hi:'कन्याश्री प्रकल्प (पश्चिम बंगाल)', ministry:'Government of West Bengal', level:'state', state_code:'WB', status:'verify', category:['women','education','cash'], benefit_type:'cash', benefit_summary_en:'Conditional cash to keep girl students in school and delay marriage.', benefit_summary_hi:'छात्राओं को पढ़ाई में बनाए रखने व विवाह टालने हेतु सशर्त नकद।', gender:'f', occupation:['student'], documents_required:['Aadhaar','School enrolment','Bank account'], application_url:'https://wbkanyashree.gov.in/', source_url:'https://wbkanyashree.gov.in/' }),
  S({ slug:'rythu-bharosa-ts', short_code:'Rythu Bharosa', name_en:'Rythu Bharosa (Telangana)', name_hi:'रायतु भरोसा (तेलंगाना)', ministry:'Government of Telangana', level:'state', state_code:'TS', status:'verify', category:['agriculture','cash'], benefit_type:'cash', benefit_summary_en:'Per-acre investment support to farmers (amount per latest state notification).', benefit_summary_hi:'किसानों को प्रति एकड़ निवेश सहायता (राशि राज्य अधिसूचना अनुसार)।', occupation:['farmer'], documents_required:['Aadhaar','Land records','Bank account'], application_url:'https://www.telangana.gov.in/', source_url:'https://www.telangana.gov.in/' }),
  S({ slug:'kanya-sumangala-up', short_code:'Kanya Sumangala', name_en:'Mukhyamantri Kanya Sumangala (Uttar Pradesh)', name_hi:'मुख्यमंत्री कन्या सुमंगला योजना', ministry:'Government of Uttar Pradesh', level:'state', state_code:'UP', status:'verify', category:['women','girl-child','cash'], benefit_type:'cash', benefit_summary_en:'Staged cash support across a girl child’s key life milestones.', benefit_summary_hi:'बेटी के जीवन के प्रमुख पड़ावों पर चरणबद्ध नकद सहायता।', gender:'f', documents_required:['Aadhaar','Bank account','Income/Residence proof'], application_url:'https://mksy.up.gov.in/', source_url:'https://mksy.up.gov.in/' }),
  S({ slug:'namo-shetkari-mh', short_code:'Namo Shetkari', name_en:'Namo Shetkari Mahasanman Nidhi (Maharashtra)', name_hi:'नमो शेतकरी महासन्मान निधि', ministry:'Government of Maharashtra', level:'state', state_code:'MH', status:'verify', category:['agriculture','cash'], benefit_type:'cash', benefit_summary_en:'₹6,000/year state top-up to PM-KISAN beneficiary farmers.', benefit_summary_hi:'पीएम-किसान लाभार्थी किसानों को ₹6,000 वार्षिक राज्य टॉप-अप।', occupation:['farmer'], documents_required:['Aadhaar','Land records','Bank account'], application_url:'https://nsmny.mahait.org/', source_url:'https://www.maharashtra.gov.in/' }),
];

let added = 0;
for (const s of NEW) {
  if (have.has(s.slug)) { console.log('skip dup:', s.slug); continue; }
  existing.push(s); have.add(s.slug); added++;
}
fs.writeFileSync(SEED, JSON.stringify(existing, null, 2) + '\n', 'utf8');
console.log(`added ${added} schemes; total now ${existing.length}`);
