"""Inject Mechanic Bike + Mechanic Car + News AI + Coach keys into strings.js.
Run once. Idempotent — re-runs append-once per language block.
"""
import re

p = 'strings.js'
s = open(p, encoding='utf-8').read()

adds = {
  'en': {
    'mb.title':'Chitti Mechanic Bike','mb.tag':"Your bike's best friend",
    'mc.title':'Chitti Mechanic Car','mc.tag':"Your car's best friend",
    'mb.tab.home':'Home','mb.tab.bike':'My Bike','mb.tab.docs':'Documents','mb.tab.alerts':'Alerts','mb.tab.ask':'Ask Chitti',
    'mc.tab.home':'Home','mc.tab.car':'My Car','mc.tab.docs':'Documents','mc.tab.alerts':'Alerts','mc.tab.ask':'Ask Chitti',
    'mb.empty.title':'Add your bike','mb.empty.sub':'Speak: My bike Hero Splendor UP32AB1234 2018 red',
    'mc.empty.title':'Add your car','mc.empty.sub':'Speak: My car Maruti Swift DL3CAB5678 2020 white',
    'mb.health.good':'Healthy','mb.health.warn':'Pay attention','mb.health.bad':'Urgent',
    'mb.helmet':'Wore your helmet? Say yes and Chitti will open Maps',
    'mb.safety.daily':'Daily safety tip',
    'mb.fairprice':'Fair price range',
    'mb.diy':'Can fix at home?',
    'mb.ask.hint':'Tell Chitti what is wrong — chain noise, mileage drop, will not start, anything',
    'na.title':'Chitti News AI + Coach','na.tag':'AI news + dynamic AI learning for every Indian',
    'na.mode.news':'AI News','na.mode.coach':'AI Coach',
    'na.profile.title':'Tell Chitti about you',
    'na.profile.q1':'What do you do?','na.profile.q1.ph':'Interior decorator, farmer, cricketer, anything',
    'na.profile.q2':'How much do you know about AI?',
    'na.profile.l0':'Nothing yet','na.profile.l1':'A little','na.profile.l2':'Good','na.profile.l3':'Strong',
    'na.profile.save':'Save profile',
    'na.story.explain':'Explain to me',
    'na.story.pin':'Pin','na.story.sources':'Source',
    'na.coach.start':'Start learning','na.coach.cert':'See certificate',
    'na.lesson.task':'Try this now',
    'na.cert.title':'Sahayai AI Certificate',
    'na.cert.next':'Recommended next certifications',
    'na.unknown':'Chitti has not seen this profession yet — researching now',
  },
  'hi': {
    'mb.title':'Chitti Mechanic Bike','mb.tag':'आपकी बाइक का सबसे अच्छा दोस्त',
    'mc.title':'Chitti Mechanic Car','mc.tag':'आपकी गाड़ी का सबसे अच्छा दोस्त',
    'mb.tab.home':'घर','mb.tab.bike':'मेरी बाइक','mb.tab.docs':'कागज़ात','mb.tab.alerts':'चेतावनी','mb.tab.ask':'Chitti Mechanic से पूछो',
    'mc.tab.home':'घर','mc.tab.car':'मेरी गाड़ी','mc.tab.docs':'कागज़ात','mc.tab.alerts':'चेतावनी','mc.tab.ask':'Chitti Mechanic से पूछो',
    'mb.empty.title':'अपनी बाइक जोड़ें','mb.empty.sub':'बोलें — मेरी बाइक Hero Splendor UP32AB1234 2018 लाल',
    'mc.empty.title':'अपनी गाड़ी जोड़ें','mc.empty.sub':'बोलें — मेरी गाड़ी Maruti Swift DL3CAB5678 2020 सफ़ेद',
    'mb.health.good':'ठीक है','mb.health.warn':'ध्यान दो','mb.health.bad':'तुरंत देखो',
    'mb.helmet':'हेलमेट पहना? हाँ बोलें तभी Maps खोलूंगी',
    'mb.safety.daily':'आज की सुरक्षा सलाह',
    'mb.fairprice':'सही दाम क्या है',
    'mb.diy':'घर पे ठीक हो सकता है?',
    'mb.ask.hint':'Chitti को बताइए क्या तकलीफ़ है',
    'na.title':'Chitti News AI + Coach','na.tag':'AI ख़बरें + हर भारतीय के लिए AI सीखना',
    'na.mode.news':'AI समाचार','na.mode.coach':'AI Coach',
    'na.profile.title':'अपने बारे में Chitti को बताइए',
    'na.profile.q1':'आप क्या करते हैं?','na.profile.q1.ph':'इंटीरियर डेकोरेटर · किसान · क्रिकेटर · कुछ भी',
    'na.profile.q2':'AI के बारे में कितना जानते हो?',
    'na.profile.l0':'बिल्कुल नहीं','na.profile.l1':'थोड़ा थोड़ा','na.profile.l2':'ठीक-ठाक','na.profile.l3':'बहुत अच्छा',
    'na.profile.save':'मेरा प्रोफ़ाइल बचाओ',
    'na.story.explain':'मुझे समझाओ',
    'na.story.pin':'पिन','na.story.sources':'स्रोत',
    'na.coach.start':'सीखना शुरू करो','na.coach.cert':'प्रमाणपत्र देखो',
    'na.lesson.task':'अभी करके देखो',
    'na.cert.title':'Sahayai AI Certificate',
    'na.cert.next':'अगला सुझाव — असली मुफ़्त certifications',
    'na.unknown':'यह पेशा Chitti के लिए नया है — अभी जान रही हूँ',
  },
  'te': {
    'mb.title':'Chitti Mechanic Bike','mb.tag':'मी Bike कु मंचि स्नेहितुडु',
    'mc.title':'Chitti Mechanic Car','mc.tag':'मी Car कु मंचि स्नेहितुडु',
    'mb.tab.home':'ఇల్లు','mb.tab.bike':'నా Bike','mb.tab.docs':'పత్రాలు','mb.tab.alerts':'హెచ్చరికలు','mb.tab.ask':'Chitti Mechanic ను అడగండి',
    'mc.tab.home':'ఇల్లు','mc.tab.car':'నా Car','mc.tab.docs':'పత్రాలు','mc.tab.alerts':'హెచ్చరికలు','mc.tab.ask':'Chitti Mechanic ను అడగండి',
    'mb.empty.title':'మీ Bike జోడించండి','mb.empty.sub':'చెప్పండి — నా Bike Hero Splendor UP32AB1234 2018 ఎరుపు',
    'mc.empty.title':'మీ Car జోడించండి','mc.empty.sub':'చెప్పండి — నా Car Maruti Swift DL3CAB5678 2020 తెల్లని',
    'mb.health.good':'బాగుంది','mb.health.warn':'జాగ్రత్త','mb.health.bad':'వెంటనే చూడండి',
    'mb.helmet':'హెల్మెట్ ధరించారా? అవును అంటేనే Maps తెరుస్తాను',
    'mb.safety.daily':'నేటి భద్రతా సూచన',
    'mb.fairprice':'సరియైన ధర',
    'mb.diy':'ఇంట్లో సరిచేయవచ్చా?',
    'mb.ask.hint':'Chitti కి చెప్పండి ఏం సమస్య',
    'na.title':'Chitti News AI + Coach','na.tag':'AI వార్తలు + ప్రతి భారతీయుని కోసం AI నేర్చుకోవడం',
    'na.mode.news':'AI వార్తలు','na.mode.coach':'AI Coach',
    'na.profile.title':'మీ గురించి Chitti కు చెప్పండి',
    'na.profile.q1':'మీరు ఏం పని చేస్తారు?','na.profile.q1.ph':'ఇంటీరియర్ డెకరేటర్ · రైతు · క్రికెటర్ · ఏదైనా',
    'na.profile.q2':'AI గురించి ఎంత తెలుసు?',
    'na.profile.l0':'ఏమీ లేదు','na.profile.l1':'కొంచెం','na.profile.l2':'బాగుంది','na.profile.l3':'చాలా బాగుంది',
    'na.profile.save':'నా ప్రొఫైల్ సేవ్ చేయండి',
    'na.story.explain':'వివరించండి',
    'na.story.pin':'పిన్','na.story.sources':'మూలం',
    'na.coach.start':'నేర్చుకోవడం మొదలుపెట్టు','na.coach.cert':'సర్టిఫికేట్ చూడు',
    'na.lesson.task':'ఇప్పుడే చేసి చూడు',
    'na.cert.title':'Sahayai AI Certificate',
    'na.cert.next':'తర్వాత సూచన — నిజమైన ಉచిత certifications',
    'na.unknown':'ఈ వృత్తి Chitti కి కొత్తది — ఇప్పుడు తెలుసుకుంటోంది',
  },
  'bn': {
    'mb.title':'Chitti Mechanic Bike','mb.tag':'আপনার Bikeএর সেরা বন্ধু',
    'mc.title':'Chitti Mechanic Car','mc.tag':'আপনার Carএর সেরা বন্ধু',
    'mb.tab.home':'ঘর','mb.tab.bike':'আমার Bike','mb.tab.docs':'কাগজপত্র','mb.tab.alerts':'সতর্কতা','mb.tab.ask':'Chitti Mechanic কে জিজ্ঞাসা',
    'mc.tab.home':'ঘর','mc.tab.car':'আমার Car','mc.tab.docs':'কাগজপত্র','mc.tab.alerts':'সতর্কতা','mc.tab.ask':'Chitti Mechanic কে জিজ্ঞাসা',
    'mb.empty.title':'আপনার Bike যোগ করুন','mb.empty.sub':'বলুন — আমার Bike Hero Splendor UP32AB1234 2018 লাল',
    'mc.empty.title':'আপনার Car যোগ করুন','mc.empty.sub':'বলুন — আমার Car Maruti Swift DL3CAB5678 2020 সাদা',
    'mb.health.good':'ভালো','mb.health.warn':'নজর দিন','mb.health.bad':'এখনই দেখুন',
    'mb.helmet':'হেলমেট পরেছেন? হ্যাঁ বললে Maps খুলব',
    'mb.safety.daily':'আজকের নিরাপত্তা টিপ',
    'mb.fairprice':'ন্যায্য দাম',
    'mb.diy':'বাড়িতে সারানো যাবে?',
    'mb.ask.hint':'Chitti কে বলুন কী সমস্যা',
    'na.title':'Chitti News AI + Coach','na.tag':'AI খবর + প্রত্যেক ভারতীয়ের জন্য AI শেখা',
    'na.mode.news':'AI সংবাদ','na.mode.coach':'AI Coach',
    'na.profile.title':'নিজের কথা Chitti কে বলুন',
    'na.profile.q1':'আপনি কী করেন?','na.profile.q1.ph':'ইন্টেরিয়র ডেকরেটর · চাষি · ক্রিকেটার · যা কিছু',
    'na.profile.q2':'AI সম্পর্কে কতটা জানেন?',
    'na.profile.l0':'কিছুই না','na.profile.l1':'একটু একটু','na.profile.l2':'ভালো','na.profile.l3':'খুব ভালো',
    'na.profile.save':'প্রোফাইল সংরক্ষণ',
    'na.story.explain':'আমাকে বুঝিয়ে দাও',
    'na.story.pin':'পিন','na.story.sources':'উৎস',
    'na.coach.start':'শেখা শুরু','na.coach.cert':'সার্টিফিকেট দেখো',
    'na.lesson.task':'এখনই করে দেখো',
    'na.cert.title':'Sahayai AI Certificate',
    'na.cert.next':'পরবর্তী পরামর্শ — সত্যিকারের ফ্রি certifications',
    'na.unknown':'এই পেশা Chitti এর কাছে নতুন — এখন জানছি',
  },
}

for code, kv in adds.items():
    payload = ','.join('"' + k + '":"' + v + '"' for k, v in kv.items()) + ','
    pat = re.compile(r'(    ' + code + r": \{.*?)(\"err\.network\":)", re.DOTALL)
    m = pat.search(s)
    if not m:
        print('miss', code); continue
    s = s[:m.start(2)] + payload + s[m.start(2):]
open(p, 'w', encoding='utf-8').write(s)
print('done. mb.title count =', s.count('"mb.title"'))
