"""Inject the new mb.* / mc.* keys needed to flip the Mechanic pages 100% per language."""
import re
p = 'strings.js'
s = open(p, encoding='utf-8').read()

ADDS = {
  'en': {
    # Header
    'ui.open_vaani':'🎙️ Open Chitti Vaani',
    'ui.cancel':'Cancel','ui.send':'Send','ui.save':'Save','ui.demo':'Demo','ui.next':'Next',
    # Home chrome
    'mb.last_service':'Last service','mb.next_service':'Next service',
    'mb.docs_expiring':'Docs expiring','mb.open_alerts':'Open alerts',
    'mb.health.ok_sub':'All good — keep riding safely',
    'mb.health.warn_sub':'Some docs / alerts need attention',
    'mb.health.bad_sub':'See a mechanic immediately',
    # My Bike form
    'mb.form.title':'My bike','mb.form.sub':'Speak or type. Everything stays on your phone.',
    'mb.form.make':'Make','mb.form.model':'Model','mb.form.reg':'Reg. number',
    'mb.form.year':'Year','mb.form.color':'Colour','mb.form.odo':'Odometer (km)',
    'mb.form.save':'Save','mb.form.voice':'🎙️ Fill by voice','mb.form.demo':'▶ Demo fill',
    # Docs
    'mb.docs.title':'Documents — all in one place',
    'mb.docs.sub':'Insurance, PUC, RC, DL, FASTag. Chitti reminds you in its own inbox — never WhatsApp.',
    'mb.docs.window':'How early to remind?',
    'mb.docs.30':'30 days before','mb.docs.7':'7 days before','mb.docs.1':'1 day before',
    'mb.docs.read':'🔊 Read aloud','mb.docs.demo':'▶ Demo',
    # Alerts
    'mb.alerts.title':'Open alerts','mb.alerts.sub':'Most urgent first. Each alert lands in Chitti\'s inbox.',
    'mb.alerts.read':'🔊 Read all',
    # Ask Chitti tab
    'mb.ask.placeholder':'Or type — "Chain noise when going fast"',
    'mb.ask.send':'Ask Chitti →',
    'mb.ask.title':'Tell Chitti the problem',
    # OBD2 (new)
    'obd.title':'🔌 OBD2 scan','obd.sub':'Already have an error code? Type it. Chitti translates it to plain language.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073',
    'obd.scan':'Translate this code','obd.disclaim':'Phase 2 will add Bluetooth direct read.',
    # Soon
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special',
    'soon.want':'👍 I want this','soon.nope':'👎',
  },
  'hi': {
    'ui.open_vaani':'🎙️ Chitti Vaani खोलो',
    'ui.cancel':'रद्द','ui.send':'भेजो','ui.save':'सेव करो','ui.demo':'डेमो','ui.next':'आगे',
    'mb.last_service':'पिछली service','mb.next_service':'अगली service',
    'mb.docs_expiring':'कागज़ात ख़त्म हो रहे','mb.open_alerts':'चेतावनी',
    'mb.health.ok_sub':'सब ठीक है — सुरक्षित चलाते रहो',
    'mb.health.warn_sub':'कुछ कागज़ात / चेतावनी देखने हैं',
    'mb.health.bad_sub':'तुरंत mechanic को दिखाएँ',
    'mb.form.title':'मेरी बाइक','mb.form.sub':'बोलकर भरें या टाइप करें। सब Chitti के पास सुरक्षित है।',
    'mb.form.make':'बनाने वाली कंपनी (Make)','mb.form.model':'मॉडल (Model)','mb.form.reg':'रजिस्ट्रेशन नंबर',
    'mb.form.year':'साल','mb.form.color':'रंग','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'सेव करो','mb.form.voice':'🎙️ बोलकर भरें','mb.form.demo':'▶ डेमो भरो',
    'mb.docs.title':'कागज़ात — सब एक जगह',
    'mb.docs.sub':'Insurance · PUC · RC · DL · FASTag — हर कागज़ की expiry track होती है। Chitti reminder अपने inbox में देती है — WhatsApp में नहीं।',
    'mb.docs.window':'Reminder कब चाहिए?',
    'mb.docs.30':'30 दिन पहले','mb.docs.7':'7 दिन पहले','mb.docs.1':'1 दिन पहले',
    'mb.docs.read':'🔊 पढ़ो','mb.docs.demo':'▶ डेमो',
    'mb.alerts.title':'सक्रिय चेतावनी','mb.alerts.sub':'सबसे ज़रूरी ऊपर। हर alert Chitti के inbox में आएगी।',
    'mb.alerts.read':'🔊 सब पढ़ो',
    'mb.ask.placeholder':'या यहाँ लिखें — "मेरी बाइक से चेन की आवाज़ आ रही है"',
    'mb.ask.send':'Chitti से पूछो ➜',
    'mb.ask.title':'Chitti को बताइए क्या तकलीफ़ है',
    'obd.title':'🔌 OBD2 कोड','obd.sub':'क्या आपके पास error code है? यहाँ लिखें — Chitti plain Hindi में समझाएगी।',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073',
    'obd.scan':'इस code का मतलब','obd.disclaim':'Phase 2 में Bluetooth direct read भी आएगा।',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special',
    'soon.want':'👍 चाहिए','soon.nope':'👎',
  },
  'bn': {
    'ui.open_vaani':'🎙️ Chitti Vaani khulun','ui.cancel':'Cancel','ui.send':'পাঠান','ui.save':'সংরক্ষণ','ui.demo':'Demo','ui.next':'এগিয়ে',
    'mb.last_service':'শেষ service','mb.next_service':'পরবর্তী service',
    'mb.docs_expiring':'কাগজপত্র শেষ হচ্ছে','mb.open_alerts':'সতর্কতা',
    'mb.health.ok_sub':'সব ঠিক আছে',
    'mb.health.warn_sub':'কিছু কাগজ / সতর্কতা দেখতে হবে',
    'mb.health.bad_sub':'এখনই mechanic-কে দেখান',
    'mb.form.title':'আমার বাইক','mb.form.sub':'বলে দিন বা টাইপ করুন। সব আপনার ফোনে নিরাপদ।',
    'mb.form.make':'কোম্পানি (Make)','mb.form.model':'মডেল','mb.form.reg':'Reg নম্বর',
    'mb.form.year':'বছর','mb.form.color':'রঙ','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'সংরক্ষণ','mb.form.voice':'🎙️ বলে দিন','mb.form.demo':'▶ Demo',
    'mb.docs.title':'কাগজপত্র — সব এক জায়গায়',
    'mb.docs.sub':'Insurance · PUC · RC · DL · FASTag — Chitti তার নিজস্ব inbox-এ reminder দেয়, WhatsApp-এ নয়।',
    'mb.docs.window':'কত দিন আগে reminder?',
    'mb.docs.30':'৩০ দিন আগে','mb.docs.7':'৭ দিন আগে','mb.docs.1':'১ দিন আগে',
    'mb.docs.read':'🔊 পড়ে শোনাও','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'সক্রিয় সতর্কতা','mb.alerts.sub':'সবচেয়ে জরুরি উপরে।',
    'mb.alerts.read':'🔊 সব পড়ো',
    'mb.ask.placeholder':'বা এখানে লিখুন — "চেইন থেকে শব্দ আসছে"',
    'mb.ask.send':'Chitti কে জিজ্ঞাসা →',
    'mb.ask.title':'Chitti কে বলুন কী সমস্যা',
    'obd.title':'🔌 OBD2 কোড','obd.sub':'Error code আছে? টাইপ করুন — Chitti সরল ভাষায় বুঝিয়ে দেবে।',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073',
    'obd.scan':'এই code-এর অর্থ','obd.disclaim':'Phase 2-এ Bluetooth direct read আসবে।',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special',
    'soon.want':'👍 চাই','soon.nope':'👎',
  },
  'te': {
    'ui.open_vaani':'🎙️ Chitti Vaani తెరువు','ui.cancel':'రద్దు','ui.send':'పంపండి','ui.save':'సేవ్','ui.demo':'Demo','ui.next':'తరువాత',
    'mb.last_service':'చివరి service','mb.next_service':'తదుపరి service',
    'mb.docs_expiring':'పత్రాలు ముగుస్తున్నాయి','mb.open_alerts':'హెచ్చరికలు',
    'mb.health.ok_sub':'అన్నీ బాగున్నాయి',
    'mb.health.warn_sub':'కొన్ని పత్రాలు చూడాలి',
    'mb.health.bad_sub':'వెంటనే mechanic ను చూడండి',
    'mb.form.title':'నా బైక్','mb.form.sub':'మాట్లాడండి లేదా టైప్ చేయండి. అన్నీ మీ ఫోన్‌లో సురక్షితంగా ఉంటాయి.',
    'mb.form.make':'తయారీదారు (Make)','mb.form.model':'మోడల్','mb.form.reg':'రిజిస్ట్రేషన్ నంబర్',
    'mb.form.year':'సంవత్సరం','mb.form.color':'రంగు','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'సేవ్','mb.form.voice':'🎙️ మాట్లాడి నింపు','mb.form.demo':'▶ Demo నింపు',
    'mb.docs.title':'పత్రాలు — అన్నీ ఒకే చోట',
    'mb.docs.sub':'Insurance · PUC · RC · DL · FASTag — Chitti తన inbox లో reminder ఇస్తుంది, WhatsApp లో కాదు.',
    'mb.docs.window':'ఎప్పుడు reminder కావాలి?',
    'mb.docs.30':'30 రోజుల ముందు','mb.docs.7':'7 రోజుల ముందు','mb.docs.1':'1 రోజు ముందు',
    'mb.docs.read':'🔊 చదవు','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'క్రియాశీల హెచ్చరికలు','mb.alerts.sub':'అత్యవసరం పైన.',
    'mb.alerts.read':'🔊 అన్నీ చదవు',
    'mb.ask.placeholder':'లేదా ఇక్కడ టైప్ చేయండి — "చైన్ నుండి శబ్దం వస్తోంది"',
    'mb.ask.send':'Chitti ను అడగండి →',
    'mb.ask.title':'Chitti కి సమస్య చెప్పండి',
    'obd.title':'🔌 OBD2 కోడ్','obd.sub':'మీ దగ్గర error code ఉందా? టైప్ చేయండి — Chitti సరళంగా అర్థం చేయించి చెబుతుంది.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073',
    'obd.scan':'ఈ code అర్థం','obd.disclaim':'Phase 2 లో Bluetooth direct read జోడిస్తాము.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special',
    'soon.want':'👍 కావాలి','soon.nope':'👎',
  },
  'ta': {
    'ui.open_vaani':'🎙️ Chitti Vaani திற','ui.cancel':'ரத்து','ui.send':'அனுப்பு','ui.save':'சேமி','ui.demo':'Demo','ui.next':'அடுத்து',
    'mb.last_service':'கடைசி service','mb.next_service':'அடுத்த service',
    'mb.docs_expiring':'ஆவணங்கள் முடிவடைகின்றன','mb.open_alerts':'எச்சரிக்கைகள்',
    'mb.health.ok_sub':'எல்லாம் சரியாக உள்ளது','mb.health.warn_sub':'சில ஆவணங்கள் கவனிக்க வேண்டும்','mb.health.bad_sub':'உடனே mechanic-ஐ பாருங்கள்',
    'mb.form.title':'என் பைக்','mb.form.sub':'பேசவும் அல்லது தட்டச்சு செய்யவும். அனைத்தும் உங்கள் தொலைபேசியில்.',
    'mb.form.make':'நிறுவனம் (Make)','mb.form.model':'மாடல்','mb.form.reg':'பதிவு எண்',
    'mb.form.year':'வருடம்','mb.form.color':'நிறம்','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'சேமி','mb.form.voice':'🎙️ பேசி நிரப்பு','mb.form.demo':'▶ Demo நிரப்பு',
    'mb.docs.title':'ஆவணங்கள் — ஒரே இடத்தில்','mb.docs.sub':'Insurance · PUC · RC · DL · FASTag',
    'mb.docs.window':'எப்போது reminder?','mb.docs.30':'30 நாள் முன்','mb.docs.7':'7 நாள் முன்','mb.docs.1':'1 நாள் முன்',
    'mb.docs.read':'🔊 படி','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'செயலில் உள்ள எச்சரிக்கைகள்','mb.alerts.sub':'அவசியமானது மேலே.','mb.alerts.read':'🔊 அனைத்தையும் படி',
    'mb.ask.placeholder':'அல்லது இங்கே எழுதவும்','mb.ask.send':'Chitti யிடம் கேள் →','mb.ask.title':'Chitti யிடம் பிரச்சினையை சொல்லுங்கள்',
    'obd.title':'🔌 OBD2 கோடு','obd.sub':'error code தெரியுமா? தட்டச்சு செய்யவும்.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073','obd.scan':'இந்த code-இன் பொருள்',
    'obd.disclaim':'Phase 2 இல் Bluetooth direct read வரும்.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special','soon.want':'👍 வேண்டும்','soon.nope':'👎',
  },
  'mr': {
    'ui.open_vaani':'🎙️ Chitti Vaani उघडा','ui.cancel':'रद्द','ui.send':'पाठवा','ui.save':'जतन','ui.demo':'Demo','ui.next':'पुढे',
    'mb.last_service':'मागील service','mb.next_service':'पुढील service',
    'mb.docs_expiring':'कागदपत्रे संपत आहेत','mb.open_alerts':'इशारे',
    'mb.health.ok_sub':'सर्व ठीक','mb.health.warn_sub':'काही कागदपत्रे पाहायला हवीत','mb.health.bad_sub':'त्वरित mechanic दाखवा',
    'mb.form.title':'माझी बाईक','mb.form.sub':'बोला किंवा टाईप करा.',
    'mb.form.make':'कंपनी (Make)','mb.form.model':'मॉडेल','mb.form.reg':'नोंदणी क्रमांक',
    'mb.form.year':'वर्ष','mb.form.color':'रंग','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'जतन','mb.form.voice':'🎙️ बोलून भरा','mb.form.demo':'▶ Demo भरा',
    'mb.docs.title':'कागदपत्रे — एका जागी','mb.docs.sub':'Insurance · PUC · RC · DL · FASTag',
    'mb.docs.window':'किती दिवस आधी reminder?','mb.docs.30':'30 दिवस आधी','mb.docs.7':'7 दिवस आधी','mb.docs.1':'1 दिवस आधी',
    'mb.docs.read':'🔊 वाचा','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'सक्रिय इशारे','mb.alerts.sub':'महत्वाचे वर.','mb.alerts.read':'🔊 सर्व वाचा',
    'mb.ask.placeholder':'किंवा इथे लिहा','mb.ask.send':'Chitti ला विचारा →','mb.ask.title':'Chitti ला अडचण सांगा',
    'obd.title':'🔌 OBD2 कोड','obd.sub':'error code माहीत आहे? टाईप करा.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073','obd.scan':'या code चा अर्थ',
    'obd.disclaim':'Phase 2 मध्ये Bluetooth direct read येईल.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special','soon.want':'👍 हवे','soon.nope':'👎',
  },
  'gu': {
    'ui.open_vaani':'🎙️ Chitti Vaani ખોલો','ui.cancel':'રદ','ui.send':'મોકલો','ui.save':'સાચવો','ui.demo':'Demo','ui.next':'આગળ',
    'mb.last_service':'છેલ્લી service','mb.next_service':'આગલી service',
    'mb.docs_expiring':'કાગળો પૂરા થઈ રહ્યા','mb.open_alerts':'ચેતવણીઓ',
    'mb.health.ok_sub':'બધું બરાબર','mb.health.warn_sub':'કેટલાક કાગળો જોવા','mb.health.bad_sub':'તરત mechanic ને બતાવો',
    'mb.form.title':'મારી બાઈક','mb.form.sub':'બોલો કે ટાઇપ કરો.',
    'mb.form.make':'કંપની (Make)','mb.form.model':'મોડેલ','mb.form.reg':'નોંધણી નંબર',
    'mb.form.year':'વર્ષ','mb.form.color':'રંગ','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'સાચવો','mb.form.voice':'🎙️ બોલીને ભરો','mb.form.demo':'▶ Demo ભરો',
    'mb.docs.title':'કાગળો','mb.docs.sub':'Insurance · PUC · RC · DL · FASTag',
    'mb.docs.window':'કેટલા દિવસ પહેલા reminder?','mb.docs.30':'30 દિવસ પહેલા','mb.docs.7':'7 દિવસ પહેલા','mb.docs.1':'1 દિવસ પહેલા',
    'mb.docs.read':'🔊 વાંચો','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'સક્રિય ચેતવણીઓ','mb.alerts.sub':'સૌથી અગત્યનું ઉપર.','mb.alerts.read':'🔊 બધું વાંચો',
    'mb.ask.placeholder':'અહીં લખો','mb.ask.send':'Chitti ને પૂછો →','mb.ask.title':'Chitti ને સમસ્યા કહો',
    'obd.title':'🔌 OBD2 કોડ','obd.sub':'error code છે? ટાઇપ કરો.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073','obd.scan':'આ code નો અર્થ',
    'obd.disclaim':'Phase 2 માં Bluetooth direct read આવશે.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special','soon.want':'👍 જોઈએ','soon.nope':'👎',
  },
  'kn': {
    'ui.open_vaani':'🎙️ Chitti Vaani ತೆರೆ','ui.cancel':'ರದ್ದು','ui.send':'ಕಳಿಸಿ','ui.save':'ಉಳಿಸಿ','ui.demo':'Demo','ui.next':'ಮುಂದೆ',
    'mb.last_service':'ಕೊನೆಯ service','mb.next_service':'ಮುಂದಿನ service',
    'mb.docs_expiring':'ದಾಖಲೆಗಳು ಮುಗಿಯುತ್ತಿವೆ','mb.open_alerts':'ಎಚ್ಚರಿಕೆಗಳು',
    'mb.health.ok_sub':'ಎಲ್ಲಾ ಸರಿ','mb.health.warn_sub':'ಕೆಲವು ದಾಖಲೆ ನೋಡಬೇಕು','mb.health.bad_sub':'ತಕ್ಷಣ mechanic ತೋರಿಸಿ',
    'mb.form.title':'ನನ್ನ ಬೈಕ್','mb.form.sub':'ಮಾತಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.',
    'mb.form.make':'ಕಂಪನಿ (Make)','mb.form.model':'ಮಾಡೆಲ್','mb.form.reg':'ನೋಂದಣಿ ಸಂಖ್ಯೆ',
    'mb.form.year':'ವರ್ಷ','mb.form.color':'ಬಣ್ಣ','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'ಉಳಿಸಿ','mb.form.voice':'🎙️ ಮಾತಾಡಿ ತುಂಬಿ','mb.form.demo':'▶ Demo',
    'mb.docs.title':'ದಾಖಲೆಗಳು','mb.docs.sub':'Insurance · PUC · RC · DL · FASTag',
    'mb.docs.window':'ಎಷ್ಟು ದಿನ ಮುಂಚೆ reminder?','mb.docs.30':'30 ದಿನ ಮುಂಚೆ','mb.docs.7':'7 ದಿನ ಮುಂಚೆ','mb.docs.1':'1 ದಿನ ಮುಂಚೆ',
    'mb.docs.read':'🔊 ಓದು','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆ','mb.alerts.sub':'ಮುಖ್ಯ ಮೇಲೆ.','mb.alerts.read':'🔊 ಎಲ್ಲ ಓದು',
    'mb.ask.placeholder':'ಇಲ್ಲಿ ಬರೆಯಿರಿ','mb.ask.send':'Chitti ಗೆ ಕೇಳಿ →','mb.ask.title':'Chitti ಗೆ ಸಮಸ್ಯೆ ಹೇಳಿ',
    'obd.title':'🔌 OBD2 ಕೋಡ್','obd.sub':'error code ಇದೆಯೇ? ಟೈಪ್ ಮಾಡಿ.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073','obd.scan':'ಈ code ಅರ್ಥ',
    'obd.disclaim':'Phase 2 ರಲ್ಲಿ Bluetooth direct read ಬರುತ್ತದೆ.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special','soon.want':'👍 ಬೇಕು','soon.nope':'👎',
  },
  'ml': {
    'ui.open_vaani':'🎙️ Chitti Vaani തുറക്കൂ','ui.cancel':'റദ്ദ്','ui.send':'അയക്കൂ','ui.save':'സംരക്ഷിക്കൂ','ui.demo':'Demo','ui.next':'അടുത്തത്',
    'mb.last_service':'അവസാന service','mb.next_service':'അടുത്ത service',
    'mb.docs_expiring':'രേഖകൾ കഴിയുന്നു','mb.open_alerts':'മുന്നറിയിപ്പുകൾ',
    'mb.health.ok_sub':'എല്ലാം ശരി','mb.health.warn_sub':'ചില രേഖകൾ കാണണം','mb.health.bad_sub':'ഉടനെ mechanic-നെ കാണിക്കൂ',
    'mb.form.title':'എന്റെ ബൈക്ക്','mb.form.sub':'പറയൂ അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യൂ.',
    'mb.form.make':'നിർമ്മാതാവ് (Make)','mb.form.model':'മോഡൽ','mb.form.reg':'രജിസ്ട്രേഷൻ നമ്പർ',
    'mb.form.year':'വർഷം','mb.form.color':'നിറം','mb.form.odo':'Odometer (KM)',
    'mb.form.save':'സംരക്ഷിക്കൂ','mb.form.voice':'🎙️ പറഞ്ഞ് നിറയ്ക്കൂ','mb.form.demo':'▶ Demo',
    'mb.docs.title':'രേഖകൾ','mb.docs.sub':'Insurance · PUC · RC · DL · FASTag',
    'mb.docs.window':'എപ്പോൾ reminder?','mb.docs.30':'30 ദിവസം മുമ്പ്','mb.docs.7':'7 ദിവസം മുമ്പ്','mb.docs.1':'1 ദിവസം മുമ്പ്',
    'mb.docs.read':'🔊 വായിക്കൂ','mb.docs.demo':'▶ Demo',
    'mb.alerts.title':'സജീവ മുന്നറിയിപ്പ്','mb.alerts.sub':'പ്രധാനം മുകളിൽ.','mb.alerts.read':'🔊 എല്ലാം വായിക്കൂ',
    'mb.ask.placeholder':'ഇവിടെ എഴുതൂ','mb.ask.send':'Chitti-യോട് ചോദിക്കൂ →','mb.ask.title':'Chitti-ക്ക് പ്രശ്നം പറയൂ',
    'obd.title':'🔌 OBD2 കോഡ്','obd.sub':'error code അറിയാമോ? ടൈപ്പ് ചെയ്യൂ.',
    'obd.code.label':'Error code','obd.code.ph':'P0420 / B0001 / C0561 / U0073','obd.scan':'ഈ code-ന്റെ അർത്ഥം',
    'obd.disclaim':'Phase 2 ൽ Bluetooth direct read വരും.',
    'soon.flag':'🔜 Launching Soon','soon.tag':'Chitti Special','soon.want':'👍 വേണം','soon.nope':'👎',
  },
}

for code, kv in ADDS.items():
    payload = ','.join('"'+k+'":"'+v+'"' for k, v in kv.items()) + ','
    pat = re.compile(r'(    ' + code + r": \{.*?)(\"err\.network\":)", re.DOTALL)
    m = pat.search(s)
    if not m:
        print('miss', code); continue
    s = s[:m.start(2)] + payload + s[m.start(2):]
open(p, 'w', encoding='utf-8').write(s)
print('mb.form.make count =', s.count('"mb.form.make"'))
