"""Inject Chitti Fashion AI keys into strings.js — 4 langs (en/hi/te/bn)."""
import re
p = 'strings.js'
s = open(p, encoding='utf-8').read()

adds = {
  'en': {
    'fa.title':'Chitti Fashion AI','fa.tag':'Personal stylist for young India',
    'fa.tab.almari':'Wardrobe','fa.tab.shopping':'Shopping','fa.tab.today':'What to wear today','fa.tab.trends':'Trends','fa.tab.coach':'Fashion AI Coach',
    'fa.privacy.title':'Your photos. Yours alone.','fa.privacy.body':'Stored on your device, never sent without your tap. DPDP 2023 compliant. Never used for AI training.',
    'fa.gender.title':'Who is Chitti styling today?','fa.gender.male':'Male','fa.gender.female':'Female','fa.gender.other':'Other / Prefer not to say',
    'fa.empty.almari.title':'Build your wardrobe',
    'fa.empty.almari.sub':'Snap a photo of each item — Chitti tags colour + category. Photos stay on your device only.',
    'fa.almari.add':'Add an item','fa.almari.stats':'Your wardrobe',
    'fa.cat.top':'Tops','fa.cat.bottom':'Bottoms','fa.cat.outfit':'Full outfits','fa.cat.foot':'Footwear','fa.cat.bag':'Bags','fa.cat.jewel':'Jewellery','fa.cat.dupatta':'Dupattas, scarves',
    'fa.occ.casual':'Casual','fa.occ.formal':'Formal','fa.occ.wedding':'Wedding','fa.occ.festive':'Festive','fa.occ.office':'Office',
    'fa.season.summer':'Summer','fa.season.winter':'Winter','fa.season.all':'All season',
    'fa.cond.new':'New','fa.cond.good':'Good','fa.cond.old':'Old',
    'fa.shop.title':'Shopping mate','fa.shop.sub':'Try-on photo or product link — Chitti rates fit, colour, wardrobe match, occasion, value.',
    'fa.shop.take':'Take try-on photo','fa.shop.upload':'Upload product photo','fa.shop.rate':'Rate this',
    'fa.shop.fit':'Fit','fa.shop.colour':'Colour','fa.shop.match':'Wardrobe match','fa.shop.occasion':'Occasion','fa.shop.value':'Value',
    'fa.today.title':'What to wear today','fa.today.sub':'Three outfits from YOUR wardrobe — never asks you to buy.',
    'fa.today.go':'Where are you going?','fa.today.need':'Any specific need?',
    'fa.today.weather':'Today’s weather','fa.today.suggest':'Suggest outfits',
    'fa.trends.title':'Trending in India','fa.trends.sub':'Daily — Instagram India, Bollywood this week, festive + budget finds.',
    'fa.trends.have':'You can recreate this','fa.trends.buy':'You’d need to buy',
    'fa.coach.title':'Fashion AI Coach','fa.coach.profile':'Who are you?','fa.coach.tools':'AI tools for fashion','fa.coach.certs':'Real free certifications','fa.coach.cert':'Sahayai Fashion AI Certificate',
    'fa.role.student':'Student','fa.role.pro':'Working professional','fa.role.designer':'Fashion designer','fa.role.boutique':'Boutique owner','fa.role.influencer':'Influencer','fa.role.curious':'Just curious',
    'fa.body.positive':'Chitti rates fit and style, never your body. Every body is beautiful.',
  },
  'hi': {
    'fa.title':'Chitti Fashion AI','fa.tag':'Young India का personal stylist',
    'fa.tab.almari':'अलमारी','fa.tab.shopping':'खरीदारी','fa.tab.today':'आज क्या पहनूँ','fa.tab.trends':'ट्रेंड','fa.tab.coach':'Fashion AI Coach',
    'fa.privacy.title':'आपकी photos सिर्फ़ आपकी हैं।',
    'fa.privacy.body':'आपके device पर ही रहती हैं। बिना आपकी मर्ज़ी कहीं नहीं जातीं। DPDP 2023 के अनुसार। AI training के लिए कभी नहीं।',
    'fa.gender.title':'Chitti आज किसका style करे?','fa.gender.male':'पुरुष','fa.gender.female':'महिला','fa.gender.other':'अन्य / बताना नहीं चाहते',
    'fa.empty.almari.title':'अपनी अलमारी बनाइए',
    'fa.empty.almari.sub':'हर कपड़े की एक photo लीजिए — Chitti रंग और श्रेणी ख़ुद टैग करेगी। Photos सिर्फ़ आपके phone पर रहती हैं।',
    'fa.almari.add':'नया item जोड़ें','fa.almari.stats':'आपकी अलमारी',
    'fa.cat.top':'ऊपर के कपड़े','fa.cat.bottom':'नीचे के कपड़े','fa.cat.outfit':'पूरा पहनावा','fa.cat.foot':'पादत्राण','fa.cat.bag':'बैग','fa.cat.jewel':'ज़ेवर','fa.cat.dupatta':'दुपट्टा, scarf',
    'fa.occ.casual':'आम','fa.occ.formal':'औपचारिक','fa.occ.wedding':'शादी','fa.occ.festive':'त्योहार','fa.occ.office':'दफ़्तर',
    'fa.season.summer':'गर्मी','fa.season.winter':'सर्दी','fa.season.all':'हर मौसम',
    'fa.cond.new':'नया','fa.cond.good':'अच्छा','fa.cond.old':'पुराना',
    'fa.shop.title':'खरीदारी साथी','fa.shop.sub':'Trial room की photo या product का link — Chitti fit, रंग, अलमारी match, मौक़ा और दाम rate करेगी।',
    'fa.shop.take':'Trial room photo लें','fa.shop.upload':'Product photo upload करें','fa.shop.rate':'Rate करें',
    'fa.shop.fit':'Fit','fa.shop.colour':'रंग','fa.shop.match':'अलमारी से match','fa.shop.occasion':'मौक़ा','fa.shop.value':'दाम-वसूल',
    'fa.today.title':'आज क्या पहनूँ','fa.today.sub':'आपकी अपनी अलमारी से 3 outfits — खरीदना नहीं है।',
    'fa.today.go':'आज कहाँ जा रहे हैं?','fa.today.need':'कोई ख़ास ज़रूरत?',
    'fa.today.weather':'आज का मौसम','fa.today.suggest':'Outfit सुझाओ',
    'fa.trends.title':'भारत में क्या trend है','fa.trends.sub':'रोज़ — Instagram India, Bollywood इस हफ़्ते, त्योहार + बजट खोज।',
    'fa.trends.have':'यह आपकी अलमारी से बन सकता है','fa.trends.buy':'यह सामान खरीदना होगा',
    'fa.coach.title':'Fashion AI Coach','fa.coach.profile':'आप कौन हैं?','fa.coach.tools':'Fashion के लिए AI tools','fa.coach.certs':'असली मुफ़्त certifications','fa.coach.cert':'Sahayai Fashion AI Certificate',
    'fa.role.student':'विद्यार्थी','fa.role.pro':'नौकरीपेशा','fa.role.designer':'फ़ैशन डिज़ाइनर','fa.role.boutique':'बुटीक चलाते हैं','fa.role.influencer':'Influencer','fa.role.curious':'बस जिज्ञासु',
    'fa.body.positive':'Chitti सिर्फ़ कपड़े का fit और style बताती है — आपके शरीर पर कोई टिप्पणी नहीं। हर शरीर सुंदर है।',
  },
  'te': {
    'fa.title':'Chitti Fashion AI','fa.tag':'Young India personal stylist',
    'fa.tab.almari':'అలమారీ','fa.tab.shopping':'షాపింగ్','fa.tab.today':'నేడు ఏం వేసుకోవాలి','fa.tab.trends':'ట్రెండ్‌లు','fa.tab.coach':'Fashion AI Coach',
    'fa.privacy.title':'మీ ఫోటోలు మీవే.',
    'fa.privacy.body':'మీ ఫోన్‌లో మాత్రమే ఉంటాయి. మీ అనుమతి లేకుండా ఎక్కడికీ వెళ్ళవు. DPDP 2023 ప్రకారం. AI training కు ఎప్పుడూ ఉపయోగించబడవు.',
    'fa.gender.title':'Chitti ఈరోజు ఎవరిని style చేయాలి?','fa.gender.male':'పురుషుడు','fa.gender.female':'స్త్రీ','fa.gender.other':'ఇతర / చెప్పదలచను',
    'fa.empty.almari.title':'మీ అలమారీ నిర్మించండి',
    'fa.empty.almari.sub':'ప్రతి బట్టకు ఒక ఫోటో — Chitti రంగు + విభాగం ట్యాగ్ చేస్తుంది. ఫోటోలు మీ ఫోన్‌లో మాత్రమే.',
    'fa.almari.add':'కొత్త item జోడించండి','fa.almari.stats':'మీ అలమారీ',
    'fa.cat.top':'పైబట్టలు','fa.cat.bottom':'క్రింది బట్టలు','fa.cat.outfit':'పూర్తి దుస్తు','fa.cat.foot':'పాదరక్షలు','fa.cat.bag':'బ్యాగ్‌లు','fa.cat.jewel':'ఆభరణాలు','fa.cat.dupatta':'దుపట్టా, స్కార్ఫ్',
    'fa.occ.casual':'సాధారణ','fa.occ.formal':'ఔపచారిక','fa.occ.wedding':'వివాహం','fa.occ.festive':'పండుగ','fa.occ.office':'కార్యాలయం',
    'fa.season.summer':'వేసవి','fa.season.winter':'శీతాకాలం','fa.season.all':'అన్ని కాలాలు',
    'fa.cond.new':'కొత్తది','fa.cond.good':'మంచిది','fa.cond.old':'పాతది',
    'fa.shop.title':'షాపింగ్ తోడు','fa.shop.sub':'Trial room ఫోటో లేదా product link — Chitti fit, రంగు, అలమారీ match, సందర్భం, ధర rate చేస్తుంది.',
    'fa.shop.take':'Trial room ఫోటో తీయండి','fa.shop.upload':'Product ఫోటో upload','fa.shop.rate':'Rate చేయండి',
    'fa.shop.fit':'Fit','fa.shop.colour':'రంగు','fa.shop.match':'అలమారీతో సరిపోతుందా','fa.shop.occasion':'సందర్భం','fa.shop.value':'ధర-విలువ',
    'fa.today.title':'నేడు ఏం వేసుకోవాలి','fa.today.sub':'మీ సొంత అలమారీ నుండి 3 outfits — కొనమని కాదు.',
    'fa.today.go':'ఈరోజు ఎక్కడికి వెళుతున్నారు?','fa.today.need':'ప్రత్యేక అవసరం ఏదైనా?',
    'fa.today.weather':'నేటి వాతావరణం','fa.today.suggest':'Outfit సూచించు',
    'fa.trends.title':'భారతదేశంలో ట్రెండ్‌లు','fa.trends.sub':'రోజూ — Instagram India, Bollywood ఈ వారం, పండుగ + బడ్జెట్ ఫైండ్స్.',
    'fa.trends.have':'మీ అలమారీలో రీక్రియేట్ చేయవచ్చు','fa.trends.buy':'ఇవి కొనాల్సి ఉంటుంది',
    'fa.coach.title':'Fashion AI Coach','fa.coach.profile':'మీరు ఎవరు?','fa.coach.tools':'Fashion కోసం AI tools','fa.coach.certs':'నిజమైన ఉచిత certifications','fa.coach.cert':'Sahayai Fashion AI Certificate',
    'fa.role.student':'విద్యార్థి','fa.role.pro':'ఉద్యోగి','fa.role.designer':'ఫ్యాషన్ డిజైనర్','fa.role.boutique':'బూటిక్ నడుపుతారు','fa.role.influencer':'Influencer','fa.role.curious':'కేవలం ఆసక్తి',
    'fa.body.positive':'Chitti దుస్తులు fit మరియు style మాత్రమే rate చేస్తుంది — మీ శరీరం గురించి ఎప్పుడూ కాదు. ప్రతి శరీరం అందమైనది.',
  },
  'bn': {
    'fa.title':'Chitti Fashion AI','fa.tag':'তরুণ ভারতের personal stylist',
    'fa.tab.almari':'আলমারি','fa.tab.shopping':'কেনাকাটা','fa.tab.today':'আজ কী পরব','fa.tab.trends':'ট্রেন্ড','fa.tab.coach':'Fashion AI Coach',
    'fa.privacy.title':'আপনার ছবি শুধুই আপনার।',
    'fa.privacy.body':'আপনার ফোনেই থাকে। আপনার অনুমতি ছাড়া কোথাও যায় না। DPDP 2023 মেনে। AI training-এ কখনো ব্যবহার হয় না।',
    'fa.gender.title':'Chitti আজ কাকে স্টাইল করবে?','fa.gender.male':'পুরুষ','fa.gender.female':'নারী','fa.gender.other':'অন্যান্য / বলতে চাই না',
    'fa.empty.almari.title':'আপনার আলমারি বানান',
    'fa.empty.almari.sub':'প্রতিটি জামাকাপড়ের ছবি তুলুন — Chitti রঙ + শ্রেণী ট্যাগ করবে। ছবি আপনার ফোনেই থাকে।',
    'fa.almari.add':'নতুন item যোগ করুন','fa.almari.stats':'আপনার আলমারি',
    'fa.cat.top':'উপরের পোশাক','fa.cat.bottom':'নিচের পোশাক','fa.cat.outfit':'পূর্ণ পোশাক','fa.cat.foot':'জুতো','fa.cat.bag':'ব্যাগ','fa.cat.jewel':'গহনা','fa.cat.dupatta':'দুপাট্টা, স্কার্ফ',
    'fa.occ.casual':'সাধারণ','fa.occ.formal':'আনুষ্ঠানিক','fa.occ.wedding':'বিয়ে','fa.occ.festive':'উৎসব','fa.occ.office':'অফিস',
    'fa.season.summer':'গ্রীষ্ম','fa.season.winter':'শীত','fa.season.all':'সব ঋতু',
    'fa.cond.new':'নতুন','fa.cond.good':'ভালো','fa.cond.old':'পুরোনো',
    'fa.shop.title':'কেনাকাটার সঙ্গী','fa.shop.sub':'Trial room ছবি বা product link — Chitti fit, রঙ, আলমারি match, উপলক্ষ, দাম rate করবে।',
    'fa.shop.take':'Trial room ছবি তুলুন','fa.shop.upload':'Product ছবি upload','fa.shop.rate':'Rate করুন',
    'fa.shop.fit':'Fit','fa.shop.colour':'রঙ','fa.shop.match':'আলমারি match','fa.shop.occasion':'উপলক্ষ','fa.shop.value':'দাম-মূল্য',
    'fa.today.title':'আজ কী পরব','fa.today.sub':'আপনার নিজের আলমারি থেকে 3 outfit — কিনতে বলছি না।',
    'fa.today.go':'আজ কোথায় যাচ্ছেন?','fa.today.need':'কোনো বিশেষ প্রয়োজন?',
    'fa.today.weather':'আজকের আবহাওয়া','fa.today.suggest':'Outfit সাজেশন',
    'fa.trends.title':'ভারতে কী ট্রেন্ড','fa.trends.sub':'প্রতিদিন — Instagram India, Bollywood এ সপ্তাহ, উৎসব + বাজেট ফাইন্ডস।',
    'fa.trends.have':'আপনার আলমারিতে এটা বানানো যাবে','fa.trends.buy':'এগুলো কিনতে হবে',
    'fa.coach.title':'Fashion AI Coach','fa.coach.profile':'আপনি কে?','fa.coach.tools':'Fashion-এর জন্য AI tools','fa.coach.certs':'সত্যিকারের ফ্রি certifications','fa.coach.cert':'Sahayai Fashion AI Certificate',
    'fa.role.student':'ছাত্র','fa.role.pro':'চাকরিজীবী','fa.role.designer':'ফ্যাশন ডিজাইনার','fa.role.boutique':'বুটিক চালান','fa.role.influencer':'Influencer','fa.role.curious':'শুধু কৌতূহল',
    'fa.body.positive':'Chitti শুধু পোশাকের fit আর style rate করে — আপনার শরীর নিয়ে কখনো নয়। প্রতিটি শরীর সুন্দর।',
  },
}

for code, kv in adds.items():
    payload = ','.join('"' + k + '":"' + v + '"' for k, v in kv.items()) + ','
    pat = re.compile(r'(    ' + code + r": \{.*?)(\"err\.network\":)", re.DOTALL)
    m = pat.search(s)
    if not m: print('miss', code); continue
    s = s[:m.start(2)] + payload + s[m.start(2):]
open(p, 'w', encoding='utf-8').write(s)
print('done. fa.title count =', s.count('"fa.title"'))
