"""Inject chai.* keys into strings.js (4 langs: en, hi, bn, te)."""
import re
p = 'strings.js'
s = open(p, encoding='utf-8').read()

adds = {
  'en': {
    'chai.title':'Chai stall talk — Chitti learns',
    'chai.sub':'Your language, your accent — from Bhojpuri to Tulu. Privacy-first, on-device.',
    'chai.cta':'Start Chai Stall Mode','chai.learned':'What did Chitti learn today?',
    'chai.consent.title':'Chai stall talk — Chitti learns',
    'chai.consent.line1':'Should Chitti start listening? I will only learn your language.',
    'chai.rule.lang':'Only language, accent, and local words',
    'chai.rule.device':'Everything stays on your phone — no audio on the server',
    'chai.rule.stop':'Stop any time you want',
    'chai.rule.no.names':'Names of people you discuss — never recorded',
    'chai.rule.no.money':'Money, account, balance — never',
    'chai.rule.no.private':'Private matters — absolutely not',
    'chai.consent.yes':'Yes, start','chai.consent.no':'No, close',
    'chai.listen.title':'Chitti is listening…',
    'chai.listen.sub':'Talk in your language — Chitti is learning words. Everything is on your phone.',
    'chai.listen.stop':'Stop and review',
    'chai.review.title':'Here is what I learned today',
    'chai.review.sub':'Mark each word right or wrong. Only right ones go forward.',
    'chai.review.next':'Continue','chai.review.discard':'Discard all',
    'chai.share.title':'Share with the Chitti community?',
    'chai.share.sub':'Your name is never sent. Only these words. Bhojpuri Chitti only emerges when 10+ users confirm each word.',
    'chai.share.yes':'Yes, share','chai.share.no':'No, just for me',
    'chai.log.title':'What Chitti has learned from you so far',
    'chai.log.clear':'Delete everything','chai.log.close':'Close',
    'chai.thanks.title':'Thank you',
    'chai.thanks.sub':'You are training the AI of Bharat. Only people like you can do this.',
    'chai.thanks.close':'Done',
  },
  'hi': {
    'chai.title':'Chai pe charcha — Chitti seekhega',
    'chai.sub':'Aapki bhasha, aapka lehza — Bhojpuri se Tulu tak. Privacy-first, on-device.',
    'chai.cta':'Chai Stall Mode shuru karo',
    'chai.learned':'Chitti ne aaj kya seekha?',
    'chai.consent.title':'Chai pe charcha — Chitti seekhega',
    'chai.consent.line1':'Kya main sunna shuru karun? Main sirf aapki bhasha seekhunga.',
    'chai.rule.lang':'Sirf bhasha, lehza, aur sthaniya shabd',
    'chai.rule.device':'Sab kuch aapke phone par — server par koi awaaz nahi',
    'chai.rule.stop':'Jab chahein band kar sakte hain',
    'chai.rule.no.names':'Logon ke naam Chitti record nahi karega',
    'chai.rule.no.money':'Paisa, account, balance — kuch nahi',
    'chai.rule.no.private':'Niji baatein — bilkul nahi',
    'chai.consent.yes':'Haan, shuru karo','chai.consent.no':'Nahi, band karo',
    'chai.listen.title':'Chitti sun rahi hai',
    'chai.listen.sub':'Apni bhasha mein baat karein — Chitti shabd seekh rahi hai. Sab kuch aapke phone par hai.',
    'chai.listen.stop':'Band karo aur dekho',
    'chai.review.title':'Aaj maine yeh seekha',
    'chai.review.sub':'Har shabd dekhein — sahi hai ya galat hai? Sirf sahi shabd aage jayenge.',
    'chai.review.next':'Aage badho','chai.review.discard':'Sab hatao',
    'chai.share.title':'Chitti community ke saath share karein?',
    'chai.share.sub':'Aapka naam kabhi nahi jayega. Sirf yeh shabd. Bhojpuri Chitti tabhi banegi jab 10 se zyada log isi shabd ko confirm karenge.',
    'chai.share.yes':'Haan, share karo','chai.share.no':'Nahi, sirf mere liye',
    'chai.log.title':'Chitti ne aaj tak yeh seekha',
    'chai.log.clear':'Sab miti do','chai.log.close':'Band karo',
    'chai.thanks.title':'Dhanyavaad',
    'chai.thanks.sub':'Aap Bharat ki AI bana rahe hain. Aapke jaise log hi yeh karte hain.',
    'chai.thanks.close':'Theek hai',
  },
  'bn': {
    'chai.title':'Chai-er adda — Chitti shikhbe',
    'chai.sub':'Apnar bhasha, apnar uchcharan — Bhojpuri theke Tulu',
    'chai.cta':'Chai Stall Mode shuru korun','chai.learned':'Chitti aaj ki shikheche?',
    'chai.consent.title':'Chai-er adda — Chitti shikhbe',
    'chai.consent.line1':'Chitti ki shune nebe? Sudhumatra apnar bhasha shikhbe.',
    'chai.rule.lang':'Sudhumatra bhasha o sthaniya shabda',
    'chai.rule.device':'Sab kichu apnar phone-e','chai.rule.stop':'Jokhon chan bondho korte paren',
    'chai.rule.no.names':'Manusher naam noy','chai.rule.no.money':'Taka, account, balance noy',
    'chai.rule.no.private':'Byaktigato kotha noy',
    'chai.consent.yes':'Han, shuru korun','chai.consent.no':'Na, bondho korun',
    'chai.listen.title':'Chitti shunche','chai.listen.sub':'Apnar bhashay kotha bolun.',
    'chai.listen.stop':'Bondho korun ar dekhun',
    'chai.review.title':'Aaj ami eta shikhechi','chai.review.sub':'Prati shabda dekhun.',
    'chai.review.next':'Egiye','chai.review.discard':'Sob sarie din',
    'chai.share.title':'Chitti community-r sathe share korben?',
    'chai.share.sub':'Apnar naam jabe na. Sudhu shabda.',
    'chai.share.yes':'Han, share','chai.share.no':'Na, sudhu amar jonyo',
    'chai.log.title':'Chitti apnar theke eta shikheche','chai.log.clear':'Sob muche din','chai.log.close':'Bondho',
    'chai.thanks.title':'Dhonyobad','chai.thanks.sub':'Apni Bharat-er AI tairi korchen.','chai.thanks.close':'Thik ache',
  },
  'te': {
    'chai.title':'Chai-lo charcha — Chitti nerchukunntundi',
    'chai.sub':'Mee bhasha, mee uchcharan','chai.cta':'Chai Stall Mode mostalu',
    'chai.learned':'Chitti eppude enti nerchukunnadi?',
    'chai.consent.title':'Chai-lo charcha — Chitti nerchukunntundi',
    'chai.consent.line1':'Chitti vinadam start cheyya? Kevalam mee bhasha nerchukuntundi.',
    'chai.rule.lang':'Kevalam bhasha, uchcharan, sthaniya padalu',
    'chai.rule.device':'Anni mee phone lone','chai.rule.stop':'Eppudaina aapavachu',
    'chai.rule.no.names':'Vyakthula perlu — eppudu kadu','chai.rule.no.money':'Dabbu, account, balance — eppudu kadu',
    'chai.rule.no.private':'Vyakthigata vishayalu — moteyu kadu',
    'chai.consent.yes':'Avunu, mostalu','chai.consent.no':'Kadu, mooyandi',
    'chai.listen.title':'Chitti vintondi','chai.listen.sub':'Mee bhashalo mataladandi.',
    'chai.listen.stop':'Aapi chudandi','chai.review.title':'Naadu nenu ivi nerchukunnaanu',
    'chai.review.sub':'Prati padaanni chudandi.','chai.review.next':'Mundu badi','chai.review.discard':'Anni teesivey',
    'chai.share.title':'Chitti community to share cheyyala?','chai.share.sub':'Mee peru velldhi. Kevalam padalu.',
    'chai.share.yes':'Avunu, share','chai.share.no':'Kadu, kevalam naakosame',
    'chai.log.title':'Chitti mee nundi ivi nerchukundi','chai.log.clear':'Anni tolagincandi','chai.log.close':'Moosi',
    'chai.thanks.title':'Dhanyavadalu','chai.thanks.sub':'Meeru Bharat AI ni nirminchutunnaaru.','chai.thanks.close':'Sare',
  },
}

for code, kv in adds.items():
    payload = ','.join('"'+k+'":"'+v+'"' for k, v in kv.items()) + ','
    pat = re.compile(r'(    ' + code + r": \{.*?)(\"err\.network\":)", re.DOTALL)
    m = pat.search(s)
    if not m:
        print('miss', code); continue
    s = s[:m.start(2)] + payload + s[m.start(2):]
open(p, 'w', encoding='utf-8').write(s)
print('chai.title count =', s.count('"chai.title"'))
