/**
 * tools/split_lang.mjs — KI-01 fix.
 * Extracts the baked `var T = {...}` dictionary from chitti_lang.full.bak.js
 * (the pre-split snapshot) and writes one per-language data file lang/<code>.js,
 * each containing ONLY that language's { "English": "translation" } pairs where a
 * real translation exists (translation truthy AND !== the English — matching the
 * runtime's lookup semantics, which treats translation===English as "no translation").
 *
 * en is NOT emitted (English = the original text). Output also writes
 * lang/_manifest.json with per-language entry counts for verification.
 *
 * Run: node tools/split_lang.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SRC = resolve(ROOT, 'chitti_lang.full.bak.js'); // the full pre-split file
const OUTDIR = resolve(ROOT, 'lang');
mkdirSync(OUTDIR, { recursive: true });

let src = readFileSync(SRC, 'utf8');
// Expose the private T + LANGS just before the public API is attached.
src = src.replace('window.Chitti.lang = {', 'globalThis.__T = T; globalThis.__LANGS = LANGS;\n  window.Chitti.lang = {');

// Minimal browser shims so the IIFE runs in Node (wireDropdown finds no <select> → returns early).
const noop = () => {};
const sandbox = {
  console,
  setTimeout, clearTimeout,
  navigator: { language: 'en' },
  localStorage: { getItem: () => null, setItem: noop, removeItem: noop },
  requestAnimationFrame: (f) => setTimeout(f, 0),
  MutationObserver: function () { this.observe = noop; this.disconnect = noop; },
  CustomEvent: function () {},
  document: {
    readyState: 'complete',
    documentElement: {},
    body: {},
    querySelector: () => null,
    querySelectorAll: () => [],
    addEventListener: noop,
    dispatchEvent: noop,
    createElement: () => ({ setAttribute: noop, appendChild: noop, style: {} }),
    createTreeWalker: () => ({ nextNode: () => null }),
  },
};
sandbox.window = sandbox;
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(src, sandbox, { filename: 'chitti_lang.full.bak.js' });

const T = sandbox.__T;
const LANGS = sandbox.__LANGS;
if (!T || !LANGS) { console.error('FAILED to extract T/LANGS'); process.exit(1); }

const keys = Object.keys(T);
console.log('Extracted T: ' + keys.length + ' English keys; ' + LANGS.length + ' languages');

function norm(s) { return String(s).replace(/\s+/g, ' ').trim(); }

const manifest = { generated_from: 'chitti_lang.full.bak.js', total_english_keys: keys.length, languages: {} };
for (const L of LANGS) {
  const code = L.code;
  if (code === 'en') continue; // English = original text, no file needed
  const map = {};
  let n = 0;
  for (const enKey of keys) {
    const entry = T[enKey];
    if (!entry) continue;
    const v = entry[code];
    const trim = norm(enKey);
    // mirror runtime lookup: skip falsy or identical-to-English (treated as untranslated)
    if (!v || norm(v) === trim) continue;
    map[enKey] = v;
    n++;
  }
  // Per-lang file: register into the runtime; fall back to a pending queue if the
  // runtime hasn't defined the registrar yet (defensive — runtime injects this).
  const json = JSON.stringify(map);
  const body =
    '/* Chitti language pack: ' + code + ' (' + n + ' strings) — generated by tools/split_lang.mjs. Do not edit by hand. */\n' +
    '(function(){var L="' + code + '",D=' + json + ';' +
    'if(window.__chittiLangRegister){window.__chittiLangRegister(L,D);}' +
    'else{(window.__chittiLangPending=window.__chittiLangPending||[]).push([L,D]);}})();\n';
  writeFileSync(resolve(OUTDIR, code + '.js'), body);
  manifest.languages[code] = n;
}
writeFileSync(resolve(OUTDIR, '_manifest.json'), JSON.stringify(manifest, null, 2));
console.log('Wrote ' + (LANGS.length - 1) + ' language packs to lang/. Counts:', JSON.stringify(manifest.languages));
