"""
services/health_file_crypto.py
------------------------------
AES-256-GCM encryption helpers for the Chitti Health File document store.

Why AES-256-GCM and not Fernet (which the chitti-vaani vault uses)?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The CHITTI_HEALTH_FILE_MASTER_SPEC.md privacy contract is explicit:
"All health files encrypted at rest (AES-256)." Fernet is AES-128 in
CBC mode with HMAC-SHA256 — it's authenticated, but it's 128-bit, not
256. We use AES-256-GCM (NIST SP 800-38D) for direct compliance with
the spec line.

Key derivation
~~~~~~~~~~~~~~
Per-user 32-byte (256-bit) key, deterministically derived from:

    HKDF-SHA256(
        ikm  = HEALTH_FILE_PEPPER || user_token,
        salt = b"chitti-health-file-v1",
        info = b"per-user-aes256-key",
        L    = 32,
    )

The server can decrypt with just (user_token, ciphertext + nonce + tag).
The server NEVER stores the raw user_token — only its sha256-hash
(matches the chitti-vaani vault user_token_hash pattern). To decrypt,
the user's device sends the raw user_token in the request body; the
server derives the key, fetches the row, decrypts, returns the bytes.

Pepper
~~~~~~
HEALTH_FILE_PEPPER must be a 32-byte secret set via env var in
production. Falls back to a dev-only string with a `log.error` warning
so the test rig works but production never silently mis-encrypts.

Loss of the pepper = total vault loss. Back it up the same way you
back up the keystore (1Password + USB).

GCM nonce
~~~~~~~~~
12 random bytes per encryption — generated by `secrets.token_bytes(12)`.
Stored alongside the ciphertext + auth tag in the DB row. NIST limit
for GCM is 2^32 messages per key before nonce reuse becomes statistically
likely; per-user keys + 12-byte nonces give us comfortable headroom.

Auth tag
~~~~~~~~
16 bytes appended by GCM. Stored as a separate `blob_tag` column for
clarity (could be appended to ciphertext, but separating makes the
schema self-documenting).
"""
from __future__ import annotations

import hashlib
import hmac
import logging
import os
import secrets
from typing import Tuple

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

log = logging.getLogger("health_file_crypto")

_DEV_PEPPER_WARNING_PRINTED = False


def _pepper() -> bytes:
    """Return the configured pepper bytes. Production sets this via env;
    dev falls back to a fixed string with a one-time WARNING log."""
    global _DEV_PEPPER_WARNING_PRINTED
    raw = os.environ.get("HEALTH_FILE_PEPPER", "").strip()
    if not raw:
        if not _DEV_PEPPER_WARNING_PRINTED:
            log.error(
                "HEALTH_FILE_PEPPER not set — using DEV default. "
                "Set a 32-byte secret in Railway env before any real user data lands.",
            )
            _DEV_PEPPER_WARNING_PRINTED = True
        raw = "chitti-health-file-DEV-NOT-FOR-PROD-pepper-v1-do-not-ship"
    return raw.encode("utf-8")


_USER_TOKEN_PEPPER_DEFAULT = "chitti-health-file-user-token-DEV-NOT-FOR-PROD-v1"


def _user_token_pepper() -> bytes:
    return os.environ.get("HEALTH_FILE_USER_TOKEN_PEPPER", _USER_TOKEN_PEPPER_DEFAULT).encode("utf-8")


def user_token_hash(user_token: str) -> str:
    """sha256-hex of (user_token + user_token_pepper). What the DB stores;
    never reversible to the raw token."""
    if not user_token:
        raise ValueError("user_token is required")
    h = hashlib.sha256()
    h.update(user_token.encode("utf-8"))
    h.update(_user_token_pepper())
    return h.hexdigest()


def _derive_key(user_token: str) -> bytes:
    """HKDF-SHA256 → 32 bytes (AES-256 key) bound to (user_token, pepper)."""
    if not user_token:
        raise ValueError("user_token is required")
    ikm = _pepper() + user_token.encode("utf-8")
    return HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=b"chitti-health-file-v1",
        info=b"per-user-aes256-key",
    ).derive(ikm)


def encrypt(user_token: str, plaintext: bytes) -> Tuple[bytes, bytes, bytes]:
    """Encrypt a blob.

    Returns: (ciphertext, nonce_12B, tag_16B). The tag is the LAST 16
    bytes of AESGCM.encrypt's output; we split it out so the DB schema
    self-documents."""
    if not isinstance(plaintext, (bytes, bytearray)):
        raise TypeError("plaintext must be bytes")
    key = _derive_key(user_token)
    nonce = secrets.token_bytes(12)
    aes = AESGCM(key)
    ct_and_tag = aes.encrypt(nonce, bytes(plaintext), associated_data=None)
    # AESGCM appends the 16-byte tag at the end of the output.
    ct  = ct_and_tag[:-16]
    tag = ct_and_tag[-16:]
    return ct, nonce, tag


def decrypt(user_token: str, ciphertext: bytes, nonce: bytes, tag: bytes) -> bytes:
    """Decrypt a blob. Raises cryptography.exceptions.InvalidTag if the
    ciphertext was tampered with OR the user_token is wrong."""
    if len(nonce) != 12:
        raise ValueError("nonce must be 12 bytes")
    if len(tag) != 16:
        raise ValueError("tag must be 16 bytes")
    key = _derive_key(user_token)
    aes = AESGCM(key)
    return aes.decrypt(nonce, bytes(ciphertext) + bytes(tag), associated_data=None)


def constant_time_compare(a: str, b: str) -> bool:
    """Wrapper around hmac.compare_digest for callers that don't want to
    import hmac themselves."""
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))
